//>>built
require({cache:{"mijit/_TemplatedMixin":function(){define("mijit/_TemplatedMixin","dojo/_base/lang,dojo/touch,./_WidgetBase,dojo/string,dojo/cache,dojo/_base/array,dojo/_base/declare,dojo/dom-construct,dojo/sniff,dojo/_base/unload".split(","),function(i,k,h,f,b,a,d,e,c,g){var n=d("dijit._TemplatedMixin",null,{templateString:null,templatePath:null,_skipNodeCache:!1,_earlyTemplatedStartup:!1,constructor:function(){this._attachPoints=[];this._attachEvents=[]},_stringRepl:function(a){var b=this.declaredClass,
c=this;return f.substitute(a,this,function(a,e){"!"==e.charAt(0)&&(a=i.getObject(e.substr(1),!1,c));if("undefined"==typeof a)throw Error(b+" template:"+e);return null==a?"":"!"==e.charAt(0)?a:a.toString().replace(/"/g,"&quot;")},this)},buildRendering:function(){if(!this.templateString)this.templateString=b(this.templatePath,{sanitize:!0});var a=n.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),c;if(i.isString(a)){if(c=e.toDom(this._stringRepl(a),this.ownerDocument),1!=
c.nodeType)throw Error("Invalid template: "+a);}else c=a.cloneNode(!0);this.domNode=c;this.inherited(arguments);this._attachTemplateNodes(c,function(a,b){return a.getAttribute(b)});this._beforeFillContent();this._fillContent(this.srcNodeRef)},_beforeFillContent:function(){},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)},_attachTemplateNodes:function(a,b){for(var c=i.isArray(a)?a:a.all||a.getElementsByTagName("*"),e=i.isArray(a)?0:-1;0>
e||c[e];e++){var g=-1==e?a:c[e];if(!this.widgetsInTemplate||!b(g,"dojoType")&&!b(g,"data-dojo-type")){var d=b(g,"dojoAttachPoint")||b(g,"data-dojo-attach-point");if(d)for(var f=d.split(/\s*,\s*/);d=f.shift();)i.isArray(this[d])?this[d].push(g):this[d]=g,this._attachPoints.push(d);if(d=b(g,"dojoAttachEvent")||b(g,"data-dojo-attach-event"))for(var f=d.split(/\s*,\s*/),h=i.trim;d=f.shift();)if(d){var n=null;-1!=d.indexOf(":")?(n=d.split(":"),d=h(n[0]),n=h(n[1])):d=h(d);n||(n=d);this._attachEvents.push(this.connect(g,
k[d]||d,n))}}}},destroyRendering:function(){a.forEach(this._attachPoints,function(a){delete this[a]},this);this._attachPoints=[];a.forEach(this._attachEvents,this.disconnect,this);this._attachEvents=[];this.inherited(arguments)}});n._templateCache={};n.getCachedTemplate=function(a,b,c){var d=n._templateCache,g=a,h=d[g];if(h){try{if(!h.ownerDocument||h.ownerDocument==(c||document))return h}catch(k){}e.destroy(h)}a=f.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return d[g]=a;b=e.toDom(a,c);if(1!=b.nodeType)throw Error("Invalid template: "+
a);return d[g]=b};c("ie")&&g.addOnWindowUnload(function(){var a=n._templateCache,b;for(b in a){var c=a[b];"object"==typeof c&&e.destroy(c);delete a[b]}});i.extend(h,{dojoAttachEvent:"",dojoAttachPoint:""});return n})},"dojo/touch":function(){define("dojo/touch","./_base/kernel,./_base/lang,./aspect,./dom,./on,./has,./mouse,./domReady,./_base/window".split(","),function(i,k,h,f,b,a,d,e,c){function g(a){return function(c,d){return b(c,a,d)}}var h=a("touch"),n=!1;a("ios")&&(a=navigator.userAgent.match(/OS ([\d_]+)/)?
RegExp.$1:"1",n=5>parseFloat(a.replace(/_/,".").replace(/_/g,"")));var B,s;h&&(e(function(){s=c.body();c.doc.addEventListener("touchstart",function(a){var c=s;s=a.target;b.emit(c,"dojotouchout",{target:c,relatedTarget:s,bubbles:!0});b.emit(s,"dojotouchover",{target:s,relatedTarget:c,bubbles:!0})},!0);b(c.doc,"touchmove",function(a){if((a=c.doc.elementFromPoint(a.pageX-(n?0:c.global.pageXOffset),a.pageY-(n?0:c.global.pageYOffset)))&&s!==a)b.emit(s,"dojotouchout",{target:s,relatedTarget:a,bubbles:!0}),
b.emit(a,"dojotouchover",{target:a,relatedTarget:s,bubbles:!0}),s=a})}),B=function(a,d){return b(c.doc,"touchmove",function(b){(a===c.doc||f.isDescendant(s,a))&&d.call(this,k.mixin({},b,{target:s,touches:b.touches,preventDefault:function(){b.preventDefault()},stopPropagation:function(){b.stopPropagation()}}))})});d={press:g(h?"touchstart":"mousedown"),move:h?B:g("mousemove"),release:g(h?"touchend":"mouseup"),cancel:h?g("touchcancel"):d.leave,over:g(h?"dojotouchover":"mouseover"),out:g(h?"dojotouchout":
"mouseout"),enter:d._eventHandler(h?"dojotouchover":"mouseover"),leave:d._eventHandler(h?"dojotouchout":"mouseout")};return i.touch=d})},"mijit/_WidgetBase":function(){define("mijit/_WidgetBase","require,dojo/_base/array,dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-class,dojo/dom-construct,dojo/dom-geometry,dojo/dom-style,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/on,dojo/ready,dojo/Stateful,dojo/topic,dojo/_base/window,./Destroyable,./registry".split(","),
function(i,k,h,f,b,a,d,e,c,g,n,B,s,y,p,q,G,D,I,w,J,C){function E(a){return function(b){e[b?"set":"remove"](this.domNode,a,b);this._set(a,b)}}s.add("dijit-legacy-requires",!y.isAsync);s("dijit-legacy-requires")&&G(0,function(){i(["dijit/_base/manager"])});var K={};return a("dijit._WidgetBase",[D,J],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:E("lang"),dir:"",_setDirAttr:E("dir"),textDir:"","class":"",_setClassAttr:{node:"domNode",type:"class"},style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,
domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:f.blankGif||i.toUrl("dojo/resources/blank.gif"),postscript:function(a,b){this.create(a,b)},create:function(a,b){this.srcNodeRef=d.byId(b);this._connects=[];this._supportingWidgets=[];if(this.srcNodeRef&&"string"==typeof this.srcNodeRef.id)this.id=this.srcNodeRef.id;if(a)this.params=a,p.mixin(this,a);this.postMixInProperties();if(!this.id)this.id=C.getUniqueId(this.declaredClass.replace(/\./g,
"_")),this.params&&delete this.params.id;this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:w.doc);this.ownerDocumentBody=w.body(this.ownerDocument);C.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var g=this.srcNodeRef;g&&g.parentNode&&this.domNode!==g&&(g.parentNode.replaceChild(this.domNode,g),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a=
this.constructor,b=a._setterAttrs;if(!b){var b=a._setterAttrs=[],c;for(c in this.attributeMap)b.push(c);var a=a.prototype,d;for(d in a)d in this.attributeMap||"_set"+d.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()})+"Attr"in a&&b.push(d)}var g={},e;for(e in this.params||{})g[e]=this[e];k.forEach(b,function(a){a in g||this[a]&&this.set(a,this[a])},this);for(e in g)this.set(e,g[e])},postMixInProperties:function(){},buildRendering:function(){if(!this.domNode)this.domNode=
this.srcNodeRef||this.ownerDocument.createElement("div");if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(k.map(a,function(a){return a+"Rtl"})));c.add(this.domNode,a)}},postCreate:function(){},startup:function(){if(!this._started)this._started=!0,k.forEach(this.getChildren(),function(a){if(!a._started&&!a._destroyed&&p.isFunction(a.startup))a.startup(),a._started=!0})},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},
destroy:function(a){function b(c){c.destroyRecursive?c.destroyRecursive(a):c.destroy&&c.destroy(a)}this._beingDestroyed=!0;this.uninitialize();k.forEach(this._connects,p.hitch(this,"disconnect"));k.forEach(this._supportingWidgets,b);this.domNode&&k.forEach(C.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);C.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?e.remove(this.domNode,
"widgetId"):g.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||g.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){k.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;p.isObject(a)?B.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(a,b,d){d=3<=arguments.length?d:this.attributeMap[a];
k.forEach(p.isArray(d)?d:[d],function(d){var g=this[d.node||d||"domNode"];switch(d.type||"attribute"){case "attribute":p.isFunction(b)&&(b=p.hitch(this,b));d=d.attribute?d.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;g.tagName?e.set(g,d,b):g.set(d,b);break;case "innerText":g.innerHTML="";g.appendChild(this.ownerDocument.createTextNode(b));break;case "innerHTML":g.innerHTML=b;break;case "class":c.replace(g,b,this[a])}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?
this[b.g]():this[a]},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var d=this[c.s];if(p.isFunction(d))var g=d.apply(this,Array.prototype.slice.call(arguments,1));else{var d=this.focusNode&&!p.isFunction(this.focusNode)?"focusNode":"domNode",e=this[d]&&this[d].tagName,f;if(f=e)if(!(f=K[e])){f=this[d];var C={},E;for(E in f)C[E.toLowerCase()]=!0;f=K[e]=C}E=f;c=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:E&&c.l in E&&
"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?d:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return g||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;this._created&&b!==c&&(this._watchCallbacks&&this._watchCallbacks(a,c,b),
this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}}))},emit:function(a,b,c){b=b||{};if(void 0===b.bubbles)b.bubbles=!0;if(void 0===b.cancelable)b.cancelable=!0;if(!b.detail)b.detail={};b.detail.widget=this;var d,g=this["on"+a];g&&(d=g.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&q.emit(this.domNode,a.toLowerCase(),b);return d},on:function(a,b){var c=this._onMap(a);return c?h.after(this,c,b,!0):this.own(q(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;
if(!c){var c=b._onMap={},d;for(d in b.prototype)/^on/.test(d)&&(c[d.replace(/^on/,"").toLowerCase()]=d)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?C.findWidgets(this.containerNode):[]},getParent:function(){return C.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,c,d){return this.own(b.connect(a,c,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(a,
b){return this.own(I.subscribe(a,p.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:n.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=B.get(this.domNode,"display")},placeAt:function(a,b){var c=!a.tagName&&C.byId(a);c&&c.addChild&&(!b||"number"===typeof b)?c.addChild(this,b):(c=c?c.containerNode&&!/after|before|replace/.test(b||"")?c.containerNode:c.domNode:d.byId(a,this.ownerDocument),g.place(this.domNode,
c,b),!this._started&&(this.getParent()||{})._started&&this.startup());return this},getTextDir:function(a,b){return b},applyTextDir:function(){},defer:function(a,b){var c=setTimeout(p.hitch(this,function(){c=null;this._destroyed||p.hitch(this,a)()}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}})})},"dojo/Stateful":function(){define("dojo/Stateful",["./_base/declare","./_base/lang","./_base/array","dojo/when"],function(i,k,h,f){return i("dojo.Stateful",null,{_attrPairNames:{},
_getAttrNames:function(b){var a=this._attrPairNames;return a[b]?a[b]:a[b]={s:"_"+b+"Setter",g:"_"+b+"Getter"}},postscript:function(b){b&&this.set(b)},_get:function(b,a){return"function"===typeof this[a.g]?this[a.g]():this[b]},get:function(b){return this._get(b,this._getAttrNames(b))},set:function(b,a){if("object"===typeof b){for(var d in b)b.hasOwnProperty(d)&&"_watchCallbacks"!=d&&this.set(d,b[d]);return this}d=this._getAttrNames(b);var e=this._get(b,d);d=this[d.s];var c;"function"===typeof d?c=
d.apply(this,Array.prototype.slice.call(arguments,1)):this[b]=a;if(this._watchCallbacks){var g=this;f(c,function(){g._watchCallbacks(b,e,a)})}return this},_changeAttrValue:function(b,a){var d=this.get(b);this[b]=a;this._watchCallbacks&&this._watchCallbacks(b,d,a);return this},watch:function(b,a){var d=this._watchCallbacks;if(!d)var e=this,d=this._watchCallbacks=function(a,b,c,g){var f=function(d){if(d)for(var d=d.slice(),g=0,f=d.length;g<f;g++)d[g].call(e,a,b,c)};f(d["_"+a]);g||f(d["*"])};!a&&"function"===
typeof b?(a=b,b="*"):b="_"+b;var c=d[b];"object"!==typeof c&&(c=d[b]=[]);c.push(a);var g={};g.unwatch=g.remove=function(){var b=h.indexOf(c,a);-1<b&&c.splice(b,1)};return g}})})},"mijit/Destroyable":function(){define("mijit/Destroyable",["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(i,k,h){return h("dijit.Destroyable",null,{destroy:function(){this._destroyed=!0},own:function(){i.forEach(arguments,function(f){var b="destroyRecursive"in f?"destroyRecursive":"destroy"in f?"destroy":
"remove",a=k.before(this,"destroy",function(a){f[b](a)}),d=k.after(f,b,function(){a.remove();d.remove()},!0)},this);return arguments}})})},"mijit/registry":function(){define("mijit/registry",["dojo/_base/array","dojo/sniff","dojo/_base/unload","dojo/_base/window","./main"],function(i,k,h,f,b){var a={},d={},e={length:0,add:function(a){if(d[a.id])throw Error("Tried to register widget with id=="+a.id+" but that id is already registered");d[a.id]=a;this.length++},remove:function(a){d[a]&&(delete d[a],
this.length--)},byId:function(a){return"string"==typeof a?d[a]:a},byNode:function(a){return d[a.getAttribute("widgetId")]},toArray:function(){var a=[],b;for(b in d)a.push(d[b]);return a},getUniqueId:function(c){var g;do g=c+"_"+(c in a?++a[c]:a[c]=0);while(d[g]);return"dijit"==b._scopeName?g:b._scopeName+"_"+g},findWidgets:function(a,b){function e(a){for(a=a.firstChild;a;a=a.nextSibling)if(1==a.nodeType){var c=a.getAttribute("widgetId");c?(c=d[c])&&f.push(c):a!==b&&e(a)}}var f=[];e(a);return f},_destroyAll:function(){b._curFocus=
null;b._prevFocus=null;b._activeStack=[];i.forEach(e.findWidgets(f.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var b=a.getAttribute&&a.getAttribute("widgetId");if(b)return d[b];a=a.parentNode}return null},_hash:d};return b.registry=e})},"mijit/main":function(){define("mijit/main",["dojo/_base/kernel"],function(i){return i.dijit})},"dojo/string":function(){define("dojo/string",["./_base/kernel","./_base/lang"],
function(i,k){var h={};k.setObject("dojo.string",h);h.rep=function(f,b){if(0>=b||!f)return"";for(var a=[];;){b&1&&a.push(f);if(!(b>>=1))break;f+=f}return a.join("")};h.pad=function(f,b,a,d){a||(a="0");f=""+f;b=h.rep(a,Math.ceil((b-f.length)/a.length));return d?f+b:b+f};h.substitute=function(f,b,a,d){d=d||i.global;a=a?k.hitch(d,a):function(a){return a};return f.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(e,c,g){e=k.getObject(c,!1,b);g&&(e=k.getObject(g,!1,d).call(d,e,c));return a(e,c).toString()})};
h.trim=String.prototype.trim?k.trim:function(f){for(var f=f.replace(/^\s+/,""),b=f.length-1;0<=b;b--)if(/\S/.test(f.charAt(b))){f=f.substring(0,b+1);break}return f};return h})},"dojo/cache":function(){define("dojo/cache",["./_base/kernel","./text"],function(i){return i.cache})},"dojo/text":function(){define("dojo/text",["./_base/kernel","require","./has","./_base/xhr"],function(i,k,h,f){var b;b=function(a,b,c){f("GET",{url:a,sync:!!b,load:c,headers:i.config.textPluginHeaders||{}})};var a={},d=function(a){if(a){var a=
a.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,""),b=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);b&&(a=b[1])}else a="";return a},e={},c={};i.cache=function(c,e,f){var h;"string"==typeof c?/\//.test(c)?(h=c,f=e):h=k.toUrl(c.replace(/\./g,"/")+(e?"/"+e:"")):(h=c+"",f=e);c=void 0!=f&&"string"!=typeof f?f.value:f;f=f&&f.sanitize;if("string"==typeof c)return a[h]=c,f?d(c):c;if(null===c)return delete a[h],null;h in a||b(h,!0,function(b){a[h]=b});return f?d(a[h]):a[h]};return{dynamic:!0,
normalize:function(a,b){var c=a.split("!"),d=c[0];return(/^\./.test(d)?b(d):d)+(c[1]?"!"+c[1]:"")},load:function(f,h,k){var f=f.split("!"),i=1<f.length,y=f[0],p=h.toUrl(f[0]),f="url:"+p,q=e,G=function(a){k(i?d(a):a)};y in a?q=a[y]:f in h.cache?q=h.cache[f]:p in a&&(q=a[p]);if(q===e)if(c[p])c[p].push(G);else{var D=c[p]=[G];b(p,!h.async,function(b){a[y]=a[p]=b;for(var d=0;d<D.length;)D[d++](b);delete c[p]})}else G(q)}}})},"mijit/_WidgetsInTemplateMixin":function(){define("mijit/_WidgetsInTemplateMixin",
["dojo/_base/array","dojo/_base/declare","dojo/parser"],function(i,k,h){return k("dijit._WidgetsInTemplateMixin",null,{_earlyTemplatedStartup:!1,widgetsInTemplate:!0,_beforeFillContent:function(){if(this.widgetsInTemplate){var f=this._startupWidgets=h.parse(this.domNode,{noStart:!this._earlyTemplatedStartup,template:!0,inherited:{dir:this.dir,lang:this.lang,textDir:this.textDir},propsThis:this,scope:"dojo"});if(!f.isFulfilled())throw Error(this.declaredClass+": parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation.");
this._attachTemplateNodes(f,function(b,a){return b[a]})}},startup:function(){i.forEach(this._startupWidgets,function(f){f&&!f._started&&f.startup&&f.startup()});this.inherited(arguments)}})})},"dojo/parser":function(){define("dojo/parser","require,./_base/kernel,./_base/lang,./_base/array,./_base/config,./_base/html,./_base/window,./_base/url,./_base/json,./aspect,./date/stamp,./Deferred,./has,./query,./on,./ready".split(","),function(i,k,h,f,b,a,d,e,c,g,n,B,s,y,p,q){function G(a){var b=a._nameCaseMap,
c=a.prototype;if(!b||b._extendCnt<I){var b=a._nameCaseMap={},d;for(d in c)"_"!==d.charAt(0)&&(b[d.toLowerCase()]=d);b._extendCnt=I}return b}function D(a){var b=a.join();if(!w[b]){for(var c=[],d=0,f=a.length;d<f;d++){var e=a[d];c[c.length]=w[e]=w[e]||h.getObject(e)||~e.indexOf("/")&&i(e)}a=c.shift();w[b]=c.length?a.createSubclass?a.createSubclass(c):a.extend.apply(a,c):a}return w[b]}var I=0;g.after(h,"extend",function(){I++},!0);var w={},J={_clearCache:function(){I++;w={}},_functionFromScript:function(a,
b){var c="",d="",e=a.getAttribute(b+"args")||a.getAttribute("args"),g=a.getAttribute("with"),e=(e||"").split(/\s*,\s*/);g&&g.length&&f.forEach(g.split(/\s*,\s*/),function(a){c+="with("+a+"){";d+="}"});return new Function(e,c+a.innerHTML+d)},instantiate:function(a,b,c){var b=b||{},c=c||{},d=(c.scope||k._scopeName)+"Type",e="data-"+(c.scope||k._scopeName)+"-",g=e+"type",h=e+"mixins",i=[];f.forEach(a,function(a){var c=d in b?b[d]:a.getAttribute(g)||a.getAttribute(d);if(c){var e=a.getAttribute(h),c=e?
[c].concat(e.split(/\s*,\s*/)):[c];i.push({node:a,types:c})}});return this._instantiate(i,b,c)},_instantiate:function(a,b,c){a=f.map(a,function(a){var d=a.ctor||D(a.types);if(!d)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(d,a.node,b,c,a.scripts,a.inherited)},this);!b._started&&!c.noStart&&f.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a},construct:function(a,b,d,i,H,x){var C;var q=a&&a.prototype,i=i||{},t={};
i.defaults&&h.mixin(t,i.defaults);x&&h.mixin(t,x);var z;s("dom-attributes-explicit")?z=b.attributes:s("dom-attributes-specified-flag")?z=f.filter(b.attributes,function(a){return a.specified}):(x=(/^input$|^img$/i.test(b.nodeName)?b:b.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),z=f.map(x.split(/\s+/),function(a){var c=a.toLowerCase();return{name:a,value:"LI"==b.nodeName&&"value"==a||"enctype"==c?b.getAttribute(c):b.getAttributeNode(c).value}}));
var l=i.scope||k._scopeName,x="data-"+l+"-",m={};"dojo"!==l&&(m[x+"props"]="data-dojo-props",m[x+"type"]="data-dojo-type",m[x+"mixins"]="data-dojo-mixins",m[l+"type"]="dojoType",m[x+"id"]="data-dojo-id");for(var l=0,j,F=[],A,r;j=z[l++];){var o=j.name,u=o.toLowerCase();j=j.value;switch(m[u]||u){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":r=j;break;case "data-dojo-id":case "jsid":A=j;break;case "data-dojo-attach-point":case "dojoattachpoint":t.dojoAttachPoint=
j;break;case "data-dojo-attach-event":case "dojoattachevent":t.dojoAttachEvent=j;break;case "class":t["class"]=b.className;break;case "style":t.style=b.style&&b.style.cssText;break;default:if(o in q||(o=G(a)[u]||o),o in q)switch(typeof q[o]){case "string":t[o]=j;break;case "number":t[o]=j.length?Number(j):NaN;break;case "boolean":t[o]="false"!=j.toLowerCase();break;case "function":t[o]=""===j||-1!=j.search(/[^\w\.]+/i)?new Function(j):h.getObject(j,!1)||new Function(j);F.push(o);break;default:u=q[o],
t[o]=u&&"length"in u?j?j.split(/\s*,\s*/):[]:u instanceof Date?""==j?new Date(""):"now"==j?new Date:n.fromISOString(j):u instanceof e?k.baseUrl+j:c.fromJson(j)}else t[o]=j}}for(l=0;l<F.length;l++)z=F[l].toLowerCase(),b.removeAttribute(z),b[z]=null;if(r)try{r=c.fromJson.call(i.propsThis,"{"+r+"}"),h.mixin(t,r)}catch(B){throw Error(B.toString()+" in data-dojo-props='"+r+"'");}h.mixin(t,d);H||(H=a&&(a._noScript||q._noScript)?[]:y("> script[type^='dojo/']",b));d=[];i=[];r=[];F=[];if(H)for(l=0;l<H.length;l++){var v=
H[l];b.removeChild(v);z=v.getAttribute(x+"event")||v.getAttribute("event");m=v.getAttribute(x+"prop");o=v.getAttribute(x+"method");u=v.getAttribute(x+"advice");j=v.getAttribute("type");v=this._functionFromScript(v,x);z?"dojo/connect"==j?d.push({method:z,func:v}):"dojo/on"==j?F.push({event:z,func:v}):t[z]=v:"dojo/aspect"==j?d.push({method:o,advice:u,func:v}):"dojo/watch"==j?r.push({prop:m,func:v}):i.push(v)}C=(H=a.markupFactory||q.markupFactory)?H(t,b,a):new a(t,b),a=C;A&&h.setObject(A,a);for(l=0;l<
d.length;l++)g[d[l].advice||"after"](a,d[l].method,h.hitch(a,d[l].func),!0);for(l=0;l<i.length;l++)i[l].call(a);for(l=0;l<r.length;l++)a.watch(r[l].prop,r[l].func);for(l=0;l<F.length;l++)p(a,F[l].event,F[l].func);return a},scan:function(a,b){function c(a){if(!a.inherited){a.inherited={};var b=a.node,d=c(a.parent),b={dir:b.getAttribute("dir")||d.dir,lang:b.getAttribute("lang")||d.lang,textDir:b.getAttribute(l)||d.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var d=[],e=[],g=
{},h=(b.scope||k._scopeName)+"Type",n="data-"+(b.scope||k._scopeName)+"-",p=n+"type",l=n+"textdir",n=n+"mixins",m=a.firstChild,j=b.inherited;if(!j){var q=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&q(a.parentNode,b)},j={dir:q(a,"dir"),lang:q(a,"lang"),textDir:q(a,l)},A;for(A in j)j[A]||delete j[A]}for(var j={inherited:j},r,o;;)if(m)if(1!=m.nodeType)m=m.nextSibling;else if(r&&"script"==m.nodeName.toLowerCase())(u=m.getAttribute("type"))&&/^dojo\/\w/i.test(u)&&r.push(m),m=
m.nextSibling;else if(o)m=m.nextSibling;else{var u=m.getAttribute(p)||m.getAttribute(h);A=m.firstChild;if(!u&&(!A||3==A.nodeType&&!A.nextSibling))m=m.nextSibling;else{o=null;if(u){var w=m.getAttribute(n);r=w?[u].concat(w.split(/\s*,\s*/)):[u];try{o=D(r)}catch(v){}o||f.forEach(r,function(a){~a.indexOf("/")&&!g[a]&&(g[a]=!0,e[e.length]=a)});w=o&&!o.prototype._noScript?[]:null;j={types:r,ctor:o,parent:j,node:m,scripts:w};j.inherited=c(j);d.push(j)}else j={node:m,scripts:r,parent:j};m=A;r=w;o=o&&o.prototype.stopParser&&
!b.template}}else{if(!j||!j.node)break;m=j.node.nextSibling;o=!1;j=j.parent;r=j.scripts}var y=new B;e.length?(s("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+e.join(", ")),i(e,function(){y.resolve(f.filter(d,function(a){if(!a.ctor)try{a.ctor=D(a.types)}catch(c){}for(var d=a.parent;d&&!d.types;)d=d.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&!b.template);a.instantiate=!d||d.instantiate&&d.instantiateChildren;return a.instantiate}))})):
y.resolve(d);return y.promise},_require:function(a){var a=c.fromJson("{"+a.innerHTML+"}"),b=[],d=[],e=new B,f;for(f in a)b.push(f),d.push(a[f]);i(d,function(){for(var a=0;a<b.length;a++)h.setObject(b[a],arguments[a]);e.resolve(arguments)});return e.promise},_scanAmd:function(a){var b=new B,c=b.promise;b.resolve(!0);var d=this;y("script[type='dojo/require']",a).forEach(function(a){c=c.then(function(){return d._require(a)});a.parentNode.removeChild(a)});return c},parse:function(b,c){var e;!c&&b&&b.rootNode?
(c=b,e=c.rootNode):b&&h.isObject(b)&&!("nodeType"in b)?c=b:e=b;e=e?a.byId(e):d.body();var c=c||{},f=c.template?{template:!0}:{},g=[],i=this,k=this._scanAmd(e,c).then(function(){return i.scan(e,c)}).then(function(a){return g=g.concat(i._instantiate(a,f,c))}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});h.mixin(g,k);return g}};k.parser=J;b.parseOnLoad&&q(100,J,"parse");return J})},"dojo/_base/url":function(){define("dojo/_base/url",["./kernel"],function(i){var k=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,
h=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,f=function(){for(var b=arguments,a=[b[0]],d=1;d<b.length;d++)if(b[d]){var e=new f(b[d]+""),a=new f(a[0]+"");if(""==e.path&&!e.scheme&&!e.authority&&!e.query){if(null!=e.fragment)a.fragment=e.fragment;e=a}else if(!e.scheme&&(e.scheme=a.scheme,!e.authority&&(e.authority=a.authority,"/"!=e.path.charAt(0)))){for(var a=(a.path.substring(0,a.path.lastIndexOf("/")+1)+e.path).split("/"),c=0;c<a.length;c++)"."==a[c]?c==a.length-1?a[c]="":(a.splice(c,
1),c--):0<c&&!(1==c&&""==a[0])&&".."==a[c]&&".."!=a[c-1]&&(c==a.length-1?(a.splice(c,1),a[c-1]=""):(a.splice(c-1,2),c-=2));e.path=a.join("/")}a=[];e.scheme&&a.push(e.scheme,":");e.authority&&a.push("//",e.authority);a.push(e.path);e.query&&a.push("?",e.query);e.fragment&&a.push("#",e.fragment)}this.uri=a.join("");b=this.uri.match(k);this.scheme=b[2]||(b[1]?"":null);this.authority=b[4]||(b[3]?"":null);this.path=b[5];this.query=b[7]||(b[6]?"":null);this.fragment=b[9]||(b[8]?"":null);if(null!=this.authority)b=
this.authority.match(h),this.user=b[3]||null,this.password=b[4]||null,this.host=b[6]||b[7],this.port=b[9]||null};f.prototype.toString=function(){return this.uri};return i._Url=f})},"dojo/date/stamp":function(){define("dojo/date/stamp",["../_base/lang","../_base/array"],function(i,k){var h={};i.setObject("dojo.date.stamp",h);h.fromISOString=function(f,b){if(!h._isoRegExp)h._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var a=
h._isoRegExp.exec(f),d=null;if(a){a.shift();a[1]&&a[1]--;a[6]&&(a[6]*=1E3);b&&(b=new Date(b),k.forEach(k.map("FullYear,Month,Date,Hours,Minutes,Seconds,Milliseconds".split(","),function(a){return b["get"+a]()}),function(b,c){a[c]=a[c]||b}));d=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);100>a[0]&&d.setFullYear(a[0]||1970);var e=0,c=a[7]&&a[7].charAt(0);"Z"!=c&&(e=60*(a[8]||0)+(Number(a[9])||0),"-"!=c&&(e*=-1));c&&(e-=d.getTimezoneOffset());e&&d.setTime(d.getTime()+6E4*e)}return d};
h.toISOString=function(f,b){var a=function(a){return 10>a?"0"+a:a},b=b||{},d=[],e=b.zulu?"getUTC":"get",c="";"time"!=b.selector&&(c=f[e+"FullYear"](),c=["0000".substr((c+"").length)+c,a(f[e+"Month"]()+1),a(f[e+"Date"]())].join("-"));d.push(c);if("date"!=b.selector){c=[a(f[e+"Hours"]()),a(f[e+"Minutes"]()),a(f[e+"Seconds"]())].join(":");e=f[e+"Milliseconds"]();b.milliseconds&&(c+="."+(100>e?"0":"")+a(e));if(b.zulu)c+="Z";else if("time"!=b.selector)var e=f.getTimezoneOffset(),g=Math.abs(e),c=c+((0<
e?"-":"+")+a(Math.floor(g/60))+":"+a(g%60));d.push(c)}return d.join("T")};return h})}}});define("frontend/layer/mijit",[],1);