//>>built
require({cache:{"dobolo/Affix":function(){define("dobolo/Affix","dojo/_base/declare,dojo/_base/lang,dojo/_base/window,dojo/on,dojo/dom-class,dojo/dom-style,dojo/dom-geometry".split(","),function(e,f,g,j,d,a,h){return e([],{offsetTop:0,offsetBottom:0,affixed:null,unpin:null,scroller:null,constructor:function(c,b){c=c||{};this.node=b;this.offsetTop=c.offsetTop||0;this.offsetBottom=c.offsetBottom||0;this.scroller=j(g.doc,"scroll",f.hitch(this,"checkPosition"));this.checkPosition()},checkPosition:function(){if("none"!==
a.get(this.node,"display")){var c=h.position(this.node,!1),b=g.doc.height,j=g.global.scrollY,e,f;e="function"===typeof this.offsetTop?this.offsetTop():this.offsetTop;f="function"===typeof this.offsetBottom?this.offsetBottom():this.offsetBottom;b=null!==this.unpin&&j+this.unpin<=c.y?!1:null!==f&&c.y+c.h>=b-f?"bottom":null!==e&&j<=e?"top":!1;if(this.affixed!==b)this.affixed=b,this.unpin="bottom"===b?c.y-j:null,d.remove(this.node,"affix affix-top affix-bottom"),d.add(this.node,"affix"+(b?"-"+b:""))}},
destroy:function(){this.scroller&&this.scroller.remove&&this.scroller.remove()}})})},"dobolo/Scrollspy":function(){define("dobolo/Scrollspy","dojo/_base/declare,./ScrollTopSpyHelper,dojo/_base/window,dojo/dom-class,dojo/dom-attr,dojo/query,dojo/on".split(","),function(e,f,g,j,d,a){return e([],{helper:null,handle:null,constructor:function(h,c){var h=h||{},c=!c||c&&"BODY"===c.tagName?g.doc:c,b=h.offsetNodeSelector?a(h.offsetNodeSelector,c):[],e=h.targetSelector?h.targetSelector:null;this.helper=new f(c,
b,h.offsetTop||0,h.wait||100);this.handle=this.helper.on("active",function(c){a(e+" li").forEach(function(b){a("> a",b).forEach(function(a){a=(d.get(a,"href")||"").replace(/^#/,"");j[a===c.node.id?"add":"remove"](b,"active")})})})},destroy:function(){this.helper.destroy();this.handle&&this.handle.remove&&this.handle.remove()}})})},"dobolo/ScrollTopSpyHelper":function(){define("dobolo/ScrollTopSpyHelper","dojo/_base/declare,dojo/Evented,dojo/dom-geometry,dojo/_base/lang,dojo/_base/window,dojo/dom,dojo/on,./Util".split(","),
function(e,f,g,j,d,a,h,c){return e([f],{scroller:null,constructor:function(b,a,e,f){var r,f=f||100,e=e||0,y=null,D=b===d.doc?0:g.position(b).y,F=c.throttle(function(c){for(r=c.length-1;0<=r;r-=1)if(g.position(c[r],!1).y<=0+e+D){if(y===c[r])break;y=c[r];this.emit("active",{bubbles:!0,cancelable:!0,node:c[r]});break}},f,this);this.scroller=h(b,"scroll",j.hitch(this,function(){node=F(a)}))},destroy:function(){this.scroller&&this.scroller.remove&&this.scroller.remove()}})})},"dobolo/Util":function(){define("dobolo/Util",
[],function(){return{transition:function(){var e;a:{e=document.createElement("bootstrap");var f={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",transition:"transitionend"},g;for(g in f)if(void 0!==e.style[g]){e=f[g];break a}e=void 0}return e&&{end:e}}(),throttle:function(e,f,g){var j=!0;return function(){j&&(j=!1,e.apply(g||e,arguments),setTimeout(function(){j=!0},f))}}}})},"dijitive/ExpandingTextarea":function(){define("dijitive/ExpandingTextarea",
["dojo/_base/declare","dojo/dom-attr","dijit/form/Textarea"],function(e,f,g){return e([g],{})})},"dijit/form/Textarea":function(){define("dijit/form/Textarea",["dojo/_base/declare","dojo/dom-style","./_ExpandingTextAreaMixin","./SimpleTextarea"],function(e,f,g,j){return e("dijit.form.Textarea",[j,g],{baseClass:"dijitTextBox dijitTextArea dijitExpandingTextArea",cols:"",buildRendering:function(){this.inherited(arguments);f.set(this.textbox,{overflowY:"hidden",overflowX:"auto",boxSizing:"border-box",
MsBoxSizing:"border-box",WebkitBoxSizing:"border-box",MozBoxSizing:"border-box"})}})})},"dijit/form/_ExpandingTextAreaMixin":function(){define("dijit/form/_ExpandingTextAreaMixin","dojo/_base/declare,dojo/dom-construct,dojo/has,dojo/_base/lang,dojo/on,dojo/_base/window,../Viewport".split(","),function(e,f,g,j,d,a,h){g.add("textarea-needs-help-shrinking",function(){var c=a.body(),b=f.create("textarea",{rows:"5",cols:"20",value:" ",style:{zoom:1,overflow:"hidden",visibility:"hidden",position:"absolute",
border:"0px solid black",padding:"0px"}},c,"last"),d=b.scrollHeight>=b.clientHeight;c.removeChild(b);return d});return e("dijit.form._ExpandingTextAreaMixin",null,{_setValueAttr:function(){this.inherited(arguments);this.resize()},postCreate:function(){this.inherited(arguments);var c=this.textbox;this.own(d(c,"scroll, focus",j.hitch(this,"_resizeLater")));c.style.overflowY="hidden";this._estimateHeight()},startup:function(){this.inherited(arguments);this.own(h.on("resize",j.hitch(this,"_resizeLater")));
this._resizeLater()},_onInput:function(c){this.inherited(arguments);this.resize()},_estimateHeight:function(){var c=this.textbox;c.style.height="auto";c.rows=(c.value.match(/\n/g)||[]).length+2},_resizeLater:function(){this.defer("resize")},resize:function(){function c(){var c=!1;if(""===b.value)b.value=" ",c=!0;var a=b.scrollHeight;if(c)b.value="";return a}var b=this.textbox;if("hidden"==b.style.overflowY)b.scrollTop=0;if(!this.busyResizing){this.busyResizing=!0;if(c()||b.offsetHeight){var a=b.style.height;
if(!/px/.test(a))a=c(),b.rows=1,b.style.height=a+"px";var a=Math.max(Math.max(b.offsetHeight,parseInt(a))-b.clientHeight,0)+c(),d=a+"px";if(d!=b.style.height)b.rows=1,b.style.height=d;if(g("textarea-needs-help-shrinking")){var j=c(),e=b.style.minHeight,f=4;b.style.minHeight=d;for(b.style.height="auto";0<a;){b.style.minHeight=Math.max(a-f,4)+"px";d=c();j-=d;a-=j;if(j<f)break;j=d;f<<=1}b.style.height=a+"px";b.style.minHeight=e}b.style.overflowY=c()>b.clientHeight?"auto":"hidden"}else this._estimateHeight();
this.busyResizing=!1}}})})},"dijit/Viewport":function(){define("dijit/Viewport","dojo/Evented,dojo/on,dojo/domReady,dojo/sniff,dojo/_base/window,dojo/window".split(","),function(e,f,g,j,d,a){var h=new e;g(function(){var c=a.getBox();h._rlh=f(d.global,"resize",function(){var b=a.getBox();c.h==b.h&&c.w==b.w||(c=b,h.emit("resize"))});if(8==j("ie")){var b=screen.deviceXDPI;setInterval(function(){if(screen.deviceXDPI!=b)b=screen.deviceXDPI,h.emit("resize")},500)}});return h})},"dojo/parser":function(){define("dojo/parser",
"require,./_base/kernel,./_base/lang,./_base/array,./_base/config,./_base/html,./_base/window,./_base/url,./_base/json,./aspect,./date/stamp,./Deferred,./has,./query,./on,./ready".split(","),function(e,f,g,j,d,a,h,c,b,w,x,C,r,y,D,F){function I(c){var a=c._nameCaseMap,b=c.prototype;if(!a||a._extendCnt<E){var a=c._nameCaseMap={},d;for(d in b)"_"!==d.charAt(0)&&(a[d.toLowerCase()]=d);a._extendCnt=E}return a}function G(a){var c=a.join();if(!A[c]){for(var b=[],d=0,j=a.length;d<j;d++){var f=a[d];b[b.length]=
A[f]=A[f]||g.getObject(f)||~f.indexOf("/")&&e(f)}a=b.shift();A[c]=b.length?a.createSubclass?a.createSubclass(b):a.extend.apply(a,b):a}return A[c]}var E=0;w.after(g,"extend",function(){E++},!0);var A={},H={_clearCache:function(){E++;A={}},_functionFromScript:function(a,c){var b="",d="",f=a.getAttribute(c+"args")||a.getAttribute("args"),e=a.getAttribute("with"),f=(f||"").split(/\s*,\s*/);e&&e.length&&j.forEach(e.split(/\s*,\s*/),function(a){b+="with("+a+"){";d+="}"});return new Function(f,b+a.innerHTML+
d)},instantiate:function(a,c,b){var c=c||{},b=b||{},d=(b.scope||f._scopeName)+"Type",e="data-"+(b.scope||f._scopeName)+"-",g=e+"type",h=e+"mixins",n=[];j.forEach(a,function(a){var b=d in c?c[d]:a.getAttribute(g)||a.getAttribute(d);if(b){var f=a.getAttribute(h),b=f?[b].concat(f.split(/\s*,\s*/)):[b];n.push({node:a,types:b})}});return this._instantiate(n,c,b)},_instantiate:function(a,b,c){a=j.map(a,function(a){var d=a.ctor||G(a.types);if(!d)throw Error("Unable to resolve constructor for: '"+a.types.join()+
"'");return this.construct(d,a.node,b,c,a.scripts,a.inherited)},this);!b._started&&!c.noStart&&j.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a},construct:function(a,d,e,h,z,s){var K;var B=a&&a.prototype,h=h||{},n={};h.defaults&&g.mixin(n,h.defaults);s&&g.mixin(n,s);var u;r("dom-attributes-explicit")?u=d.attributes:r("dom-attributes-specified-flag")?u=j.filter(d.attributes,function(a){return a.specified}):(s=(/^input$|^img$/i.test(d.nodeName)?d:d.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,
"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),u=j.map(s.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:"LI"==d.nodeName&&"value"==a||"enctype"==b?d.getAttribute(b):d.getAttributeNode(b).value}}));var k=h.scope||f._scopeName,s="data-"+k+"-",l={};"dojo"!==k&&(l[s+"props"]="data-dojo-props",l[s+"type"]="data-dojo-type",l[s+"mixins"]="data-dojo-mixins",l[k+"type"]="dojoType",l[s+"id"]="data-dojo-id");for(var k=0,i,t=[],v,o;i=u[k++];){var m=i.name,p=m.toLowerCase();i=
i.value;switch(l[p]||p){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":o=i;break;case "data-dojo-id":case "jsid":v=i;break;case "data-dojo-attach-point":case "dojoattachpoint":n.dojoAttachPoint=i;break;case "data-dojo-attach-event":case "dojoattachevent":n.dojoAttachEvent=i;break;case "class":n["class"]=d.className;break;case "style":n.style=d.style&&d.style.cssText;break;default:if(m in B||(m=I(a)[p]||m),m in B)switch(typeof B[m]){case "string":n[m]=i;
break;case "number":n[m]=i.length?Number(i):NaN;break;case "boolean":n[m]="false"!=i.toLowerCase();break;case "function":n[m]=""===i||-1!=i.search(/[^\w\.]+/i)?new Function(i):g.getObject(i,!1)||new Function(i);t.push(m);break;default:p=B[m],n[m]=p&&"length"in p?i?i.split(/\s*,\s*/):[]:p instanceof Date?""==i?new Date(""):"now"==i?new Date:x.fromISOString(i):p instanceof c?f.baseUrl+i:b.fromJson(i)}else n[m]=i}}for(k=0;k<t.length;k++)u=t[k].toLowerCase(),d.removeAttribute(u),d[u]=null;if(o)try{o=
b.fromJson.call(h.propsThis,"{"+o+"}"),g.mixin(n,o)}catch(J){throw Error(J.toString()+" in data-dojo-props='"+o+"'");}g.mixin(n,e);z||(z=a&&(a._noScript||B._noScript)?[]:y("> script[type^='dojo/']",d));e=[];h=[];o=[];t=[];if(z)for(k=0;k<z.length;k++){var q=z[k];d.removeChild(q);u=q.getAttribute(s+"event")||q.getAttribute("event");l=q.getAttribute(s+"prop");m=q.getAttribute(s+"method");p=q.getAttribute(s+"advice");i=q.getAttribute("type");q=this._functionFromScript(q,s);u?"dojo/connect"==i?e.push({method:u,
func:q}):"dojo/on"==i?t.push({event:u,func:q}):n[u]=q:"dojo/aspect"==i?e.push({method:m,advice:p,func:q}):"dojo/watch"==i?o.push({prop:l,func:q}):h.push(q)}K=(z=a.markupFactory||B.markupFactory)?z(n,d,a):new a(n,d),a=K;v&&g.setObject(v,a);for(k=0;k<e.length;k++)w[e[k].advice||"after"](a,e[k].method,g.hitch(a,e[k].func),!0);for(k=0;k<h.length;k++)h[k].call(a);for(k=0;k<o.length;k++)a.watch(o[k].prop,o[k].func);for(k=0;k<t.length;k++)D(a,t[k].event,t[k].func);return a},scan:function(a,b){function c(a){if(!a.inherited){a.inherited=
{};var b=a.node,d=c(a.parent),b={dir:b.getAttribute("dir")||d.dir,lang:b.getAttribute("lang")||d.lang,textDir:b.getAttribute(k)||d.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var d=[],h=[],g={},D=(b.scope||f._scopeName)+"Type",n="data-"+(b.scope||f._scopeName)+"-",y=n+"type",k=n+"textdir",n=n+"mixins",l=a.firstChild,i=b.inherited;if(!i){var t=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&t(a.parentNode,b)},i={dir:t(a,"dir"),lang:t(a,"lang"),textDir:t(a,
k)},v;for(v in i)i[v]||delete i[v]}for(var i={inherited:i},o,m;;)if(l)if(1!=l.nodeType)l=l.nextSibling;else if(o&&"script"==l.nodeName.toLowerCase())(p=l.getAttribute("type"))&&/^dojo\/\w/i.test(p)&&o.push(l),l=l.nextSibling;else if(m)l=l.nextSibling;else{var p=l.getAttribute(y)||l.getAttribute(D);v=l.firstChild;if(!p&&(!v||3==v.nodeType&&!v.nextSibling))l=l.nextSibling;else{m=null;if(p){var w=l.getAttribute(n);o=w?[p].concat(w.split(/\s*,\s*/)):[p];try{m=G(o)}catch(q){}m||j.forEach(o,function(a){~a.indexOf("/")&&
!g[a]&&(g[a]=!0,h[h.length]=a)});w=m&&!m.prototype._noScript?[]:null;i={types:o,ctor:m,parent:i,node:l,scripts:w};i.inherited=c(i);d.push(i)}else i={node:l,scripts:o,parent:i};l=v;o=w;m=m&&m.prototype.stopParser&&!b.template}}else{if(!i||!i.node)break;l=i.node.nextSibling;m=!1;i=i.parent;o=i.scripts}var x=new C;h.length?(r("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+h.join(", ")),e(h,function(){x.resolve(j.filter(d,function(a){if(!a.ctor)try{a.ctor=G(a.types)}catch(c){}for(var d=
a.parent;d&&!d.types;)d=d.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&!b.template);a.instantiate=!d||d.instantiate&&d.instantiateChildren;return a.instantiate}))})):x.resolve(d);return x.promise},_require:function(a){var a=b.fromJson("{"+a.innerHTML+"}"),c=[],d=[],f=new C,h;for(h in a)c.push(h),d.push(a[h]);e(d,function(){for(var a=0;a<c.length;a++)g.setObject(c[a],arguments[a]);f.resolve(arguments)});return f.promise},_scanAmd:function(a){var b=new C,c=b.promise;
b.resolve(!0);var d=this;y("script[type='dojo/require']",a).forEach(function(a){c=c.then(function(){return d._require(a)});a.parentNode.removeChild(a)});return c},parse:function(b,c){var d;!c&&b&&b.rootNode?(c=b,d=c.rootNode):b&&g.isObject(b)&&!("nodeType"in b)?c=b:d=b;d=d?a.byId(d):h.body();var c=c||{},e=c.template?{template:!0}:{},f=[],j=this,r=this._scanAmd(d,c).then(function(){return j.scan(d,c)}).then(function(a){return f=f.concat(j._instantiate(a,e,c))}).otherwise(function(a){console.error("dojo/parser::parse() error",
a);throw a;});g.mixin(f,r);return f}};f.parser=H;d.parseOnLoad&&F(100,H,"parse");return H})},"dojo/_base/url":function(){define("dojo/_base/url",["./kernel"],function(e){var f=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,g=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,j=function(){for(var d=arguments,a=[d[0]],e=1;e<d.length;e++)if(d[e]){var c=new j(d[e]+""),a=new j(a[0]+"");if(""==c.path&&!c.scheme&&!c.authority&&!c.query){if(null!=c.fragment)a.fragment=c.fragment;
c=a}else if(!c.scheme&&(c.scheme=a.scheme,!c.authority&&(c.authority=a.authority,"/"!=c.path.charAt(0)))){for(var a=(a.path.substring(0,a.path.lastIndexOf("/")+1)+c.path).split("/"),b=0;b<a.length;b++)"."==a[b]?b==a.length-1?a[b]="":(a.splice(b,1),b--):0<b&&!(1==b&&""==a[0])&&".."==a[b]&&".."!=a[b-1]&&(b==a.length-1?(a.splice(b,1),a[b-1]=""):(a.splice(b-1,2),b-=2));c.path=a.join("/")}a=[];c.scheme&&a.push(c.scheme,":");c.authority&&a.push("//",c.authority);a.push(c.path);c.query&&a.push("?",c.query);
c.fragment&&a.push("#",c.fragment)}this.uri=a.join("");d=this.uri.match(f);this.scheme=d[2]||(d[1]?"":null);this.authority=d[4]||(d[3]?"":null);this.path=d[5];this.query=d[7]||(d[6]?"":null);this.fragment=d[9]||(d[8]?"":null);if(null!=this.authority)d=this.authority.match(g),this.user=d[3]||null,this.password=d[4]||null,this.host=d[6]||d[7],this.port=d[9]||null};j.prototype.toString=function(){return this.uri};return e._Url=j})},"dojo/date/stamp":function(){define("dojo/date/stamp",["../_base/lang",
"../_base/array"],function(e,f){var g={};e.setObject("dojo.date.stamp",g);g.fromISOString=function(e,d){if(!g._isoRegExp)g._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var a=g._isoRegExp.exec(e),h=null;if(a){a.shift();a[1]&&a[1]--;a[6]&&(a[6]*=1E3);d&&(d=new Date(d),f.forEach(f.map("FullYear,Month,Date,Hours,Minutes,Seconds,Milliseconds".split(","),function(a){return d["get"+a]()}),function(b,c){a[c]=a[c]||b}));h=new Date(a[0]||
1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);100>a[0]&&h.setFullYear(a[0]||1970);var c=0,b=a[7]&&a[7].charAt(0);"Z"!=b&&(c=60*(a[8]||0)+(Number(a[9])||0),"-"!=b&&(c*=-1));b&&(c-=h.getTimezoneOffset());c&&h.setTime(h.getTime()+6E4*c)}return h};g.toISOString=function(e,d){var a=function(a){return 10>a?"0"+a:a},d=d||{},f=[],c=d.zulu?"getUTC":"get",b="";"time"!=d.selector&&(b=e[c+"FullYear"](),b=["0000".substr((b+"").length)+b,a(e[c+"Month"]()+1),a(e[c+"Date"]())].join("-"));f.push(b);if("date"!=
d.selector){b=[a(e[c+"Hours"]()),a(e[c+"Minutes"]()),a(e[c+"Seconds"]())].join(":");c=e[c+"Milliseconds"]();d.milliseconds&&(b+="."+(100>c?"0":"")+a(c));if(d.zulu)b+="Z";else if("time"!=d.selector)var c=e.getTimezoneOffset(),g=Math.abs(c),b=b+((0<c?"-":"+")+a(Math.floor(g/60))+":"+a(g%60));f.push(b)}return f.join("T")};return g})}}});
require("dobolo/Affix,dobolo/Scrollspy,dijitive/Button,dijitive/Checkbox,dijitive/Radio,dijitive/Select,dijitive/Textarea,dijitive/ExpandingTextarea,dijitive/Textbox,dojo/_base/window,dojo/query,dojo/parser,dojo/domReady!".split(","),function(e,f,g,j,d,a,h,c,b,w,x,C){C.parse();hljs.initHighlightingOnLoad();new e({offsetTop:function(){return 980>=document.width?245:195}},x(".bs-docs-sidenav")[0]);new f({targetSelector:".bs-docs-sidenav",offsetNodeSelector:"section.spy",offsetTop:70,wait:50},w.body());
(new g({type:"submit","class":"btn btn-primary",label:'<i class="icon-music icon-white"></i> La La Laaaa',onClick:function(){console.info("Clicked");return!1}},"button1")).startup();(new j({name:"menu",value:"clam chowder",checked:!0,onChange:function(){console.info("New value is: "+this.get("value"))}},"checkbox1")).startup();(new d({name:"size",value:"large",onChange:function(){console.info("New value is: "+this.get("value"))}},"radio1")).startup();(new d({name:"size",value:"small",checked:!0,onChange:function(){console.info("New value is: "+
this.get("value"))}},"radio2")).startup();e=[{value:"",label:"Please select"},{value:"steak-and-lobster",label:"Steak & Lobster"},{value:"clam-chowder",label:"Clam chowder"},{value:"pizza",label:"Pizza",disabled:!0},{value:"pasta",label:"Pasta"}];f=new a({name:"meal1",value:"pasta",options:e,required:!0,onChange:function(a){console.info("select.onChange(): "+a)}},"select1");f.watch("value",function(a,b,c){console.info('select.watch("value")',a,b,c)});f.watch("message",function(a,b,c){console[c?"error":
"info"]('select.watch("message"):',c)});f.startup();a=new a({multiple:!0,name:"meal2",value:["steak-and-lobster","clam-chowder"],options:e,required:!0,onChange:function(a){console.info("select.onChange(): "+a)}},"select2");a.watch("value",function(a,b,c){console.info('select.watch("value")',a,b,c)});a.watch("message",function(a,b,c){console[c?"error":"info"]('select.watch("message"):',c)});a.startup();h=new h({name:"note",autocomplete:!1,uppercase:!0,trim:!0,onKeyPress:function(){console.info("Key pressed")}},
"textarea1");h.startup();h.watch("value",function(a,b,c){console.info('New value is "'+c)});c=new c({name:"note",autocomplete:!1,uppercase:!0,trim:!0,onKeyPress:function(){console.info("Key pressed")}},"expandingTextarea1");c.startup();c.watch("value",function(a,b,c){console.info('New value is "'+c)});b=new b({name:"title",placeHolder:"Your title",autocomplete:!1,uppercase:!0,trim:!0,onKeyPress:function(){console.info("Key pressed")}},"textbox1");b.startup();b.watch("value",function(a,b,c){console.info('New value is "'+
c)})});