//>>built
require({cache:{"dojo/_base/html":function(){define("dojo/_base/html","./kernel,../dom,../dom-style,../dom-attr,../dom-prop,../dom-class,../dom-construct,../dom-geometry".split(","),function(a,i,l,k,j,m,o,f){a.byId=i.byId;a.isDescendant=i.isDescendant;a.setSelectable=i.setSelectable;a.getAttr=k.get;a.setAttr=k.set;a.hasAttr=k.has;a.removeAttr=k.remove;a.getNodeProp=k.getNodeProp;a.attr=function(a,c,b){return 2==arguments.length?k["string"==typeof c?"get":"set"](a,c):k.set(a,c,b)};a.hasClass=m.contains;
a.addClass=m.add;a.removeClass=m.remove;a.toggleClass=m.toggle;a.replaceClass=m.replace;a._toDom=a.toDom=o.toDom;a.place=o.place;a.create=o.create;a.empty=function(a){o.empty(a)};a._destroyElement=a.destroy=function(a){o.destroy(a)};a._getPadExtents=a.getPadExtents=f.getPadExtents;a._getBorderExtents=a.getBorderExtents=f.getBorderExtents;a._getPadBorderExtents=a.getPadBorderExtents=f.getPadBorderExtents;a._getMarginExtents=a.getMarginExtents=f.getMarginExtents;a._getMarginSize=a.getMarginSize=f.getMarginSize;
a._getMarginBox=a.getMarginBox=f.getMarginBox;a.setMarginBox=f.setMarginBox;a._getContentBox=a.getContentBox=f.getContentBox;a.setContentSize=f.setContentSize;a._isBodyLtr=a.isBodyLtr=f.isBodyLtr;a._docScroll=a.docScroll=f.docScroll;a._getIeDocumentElementOffset=a.getIeDocumentElementOffset=f.getIeDocumentElementOffset;a._fixIeBiDiScrollLeft=a.fixIeBiDiScrollLeft=f.fixIeBiDiScrollLeft;a.position=f.position;a.marginBox=function(a,c){return c?f.setMarginBox(a,c):f.getMarginBox(a)};a.contentBox=function(a,
c){return c?f.setContentSize(a,c):f.getContentBox(a)};a.coords=function(d,c){a.deprecated("dojo.coords()","Use dojo.position() or dojo.marginBox().");var d=i.byId(d),b=l.getComputedStyle(d),b=f.getMarginBox(d,b),e=f.position(d,c);b.x=e.x;b.y=e.y;return b};a.getProp=j.get;a.setProp=j.set;a.prop=function(a,c,b){return 2==arguments.length?j["string"==typeof c?"get":"set"](a,c):j.set(a,c,b)};a.getStyle=l.get;a.setStyle=l.set;a.getComputedStyle=l.getComputedStyle;a.__toPixelValue=a.toPixelValue=l.toPixelValue;
a.style=function(a,c,b){switch(arguments.length){case 1:return l.get(a);case 2:return l["string"==typeof c?"get":"set"](a,c)}return l.set(a,c,b)};return a})},"dojo/dom-attr":function(){define("dojo/dom-attr","exports,./sniff,./_base/lang,./dom,./dom-style,./dom-prop".split(","),function(a,i,l,k,j,m){function o(a,b){var d=a.getAttributeNode&&a.getAttributeNode(b);return d&&d.specified}var f={innerHTML:1,className:1,htmlFor:i("ie"),value:1},d={classname:"class",htmlfor:"for",tabindex:"tabIndex",readonly:"readOnly"};
a.has=function(a,b){var e=b.toLowerCase();return f[m.names[e]||b]||o(k.byId(a),d[e]||b)};a.get=function(a,b){var a=k.byId(a),e=b.toLowerCase(),n=m.names[e]||b,g=a[n];if(f[n]&&"undefined"!=typeof g||"href"!=n&&("boolean"==typeof g||l.isFunction(g)))return g;e=d[e]||b;return o(a,e)?a.getAttribute(e):null};a.set=function(c,b,e){c=k.byId(c);if(2==arguments.length){for(var n in b)a.set(c,n,b[n]);return c}n=b.toLowerCase();var g=m.names[n]||b,h=f[g];if("style"==g&&"string"!=typeof e)return j.set(c,e),c;
if(h||"boolean"==typeof e||l.isFunction(e))return m.set(c,b,e);c.setAttribute(d[n]||b,e);return c};a.remove=function(a,b){k.byId(a).removeAttribute(d[b.toLowerCase()]||b)};a.getNodeProp=function(a,b){var a=k.byId(a),e=b.toLowerCase(),f=m.names[e]||b;if(f in a&&"href"!=f)return a[f];e=d[e]||b;return o(a,e)?a.getAttribute(e):null}})},"dojo/dom-prop":function(){define("dojo/dom-prop","exports,./_base/kernel,./sniff,./_base/lang,./dom,./dom-style,./dom-construct,./_base/connect".split(","),function(a,
i,l,k,j,m,o,f){var d={},c=0,b=i._scopeName+"attrid";a.names={"class":"className","for":"htmlFor",tabindex:"tabIndex",readonly:"readOnly",colspan:"colSpan",frameborder:"frameBorder",rowspan:"rowSpan",valuetype:"valueType"};a.get=function(d,b){var d=j.byId(d),c=b.toLowerCase();return d[a.names[c]||b]};a.set=function(e,n,g){e=j.byId(e);if(2==arguments.length&&"string"!=typeof n){for(var h in n)a.set(e,h,n[h]);return e}h=n.toLowerCase();h=a.names[h]||n;if("style"==h&&"string"!=typeof g)return m.set(e,
g),e;if("innerHTML"==h)return l("ie")&&e.tagName.toLowerCase()in{col:1,colgroup:1,table:1,tbody:1,tfoot:1,thead:1,tr:1,title:1}?(o.empty(e),e.appendChild(o.toDom(g,e.ownerDocument))):e[h]=g,e;if(k.isFunction(g)){var i=e[b];i||(i=c++,e[b]=i);d[i]||(d[i]={});var r=d[i][h];if(r)f.disconnect(r);else try{delete e[h]}catch(s){}g?d[i][h]=f.connect(e,h,g):e[h]=null;return e}e[h]=g;return e}})},"dojo/dom-construct":function(){define("dojo/dom-construct","exports,./_base/kernel,./sniff,./_base/window,./dom,./dom-attr,./on".split(","),
function(a,i,l,k,j,m,o){function f(a,d){var b=d.parentNode;b&&b.insertBefore(a,d)}var d={option:["select"],tbody:["table"],thead:["table"],tfoot:["table"],tr:["table","tbody"],td:["table","tbody","tr"],th:["table","thead","tr"],legend:["fieldset"],caption:["table"],colgroup:["table"],col:["table","colgroup"],li:["ul"]},c=/<\s*([\w\:]+)/,b={},e=0,n="__"+i._scopeName+"ToDomId",g;for(g in d)if(d.hasOwnProperty(g))i=d[g],i.pre="option"==g?'<select multiple="multiple">':"<"+i.join("><")+">",i.post="</"+
i.reverse().join("></")+">";var h=null,q;o(window,"unload",function(){h=null});a.toDom=function(a,f){var f=f||k.doc,p=f[n];p||(f[n]=p=++e+"",b[p]=f.createElement("div"));var a=a+"",g=a.match(c),h=g?g[1].toLowerCase():"",p=b[p];if(g&&d[h]){g=d[h];p.innerHTML=g.pre+a+g.post;for(g=g.length;g;--g)p=p.firstChild}else p.innerHTML=a;if(1==p.childNodes.length)return p.removeChild(p.firstChild);for(h=f.createDocumentFragment();g=p.firstChild;)h.appendChild(g);return h};a.place=function(d,b,c){b=j.byId(b);
"string"==typeof d&&(d=/^\s*</.test(d)?a.toDom(d,b.ownerDocument):j.byId(d));if("number"==typeof c){var e=b.childNodes;!e.length||e.length<=c?b.appendChild(d):f(d,e[0>c?0:c])}else switch(c){case "before":f(d,b);break;case "after":c=d;(e=b.parentNode)&&(e.lastChild==b?e.appendChild(c):e.insertBefore(c,b.nextSibling));break;case "replace":b.parentNode.replaceChild(d,b);break;case "only":a.empty(b);b.appendChild(d);break;case "first":if(b.firstChild){f(d,b.firstChild);break}default:b.appendChild(d)}return d};
a.create=function(d,b,c,e){var f=k.doc;if(c)c=j.byId(c),f=c.ownerDocument;"string"==typeof d&&(d=f.createElement(d));b&&m.set(d,b);c&&a.place(d,c,e);return d};a.empty=l("ie")?function(d){for(var d=j.byId(d),b;b=d.lastChild;)a.destroy(b)}:function(a){j.byId(a).innerHTML=""};a.destroy=function(a){a=j.byId(a);try{var d=a.ownerDocument;if(!h||q!=d)h=d.createElement("div"),q=d;h.appendChild(a.parentNode?a.parentNode.removeChild(a):a);h.innerHTML=""}catch(b){}}})},"dojo/dom-class":function(){define("dojo/dom-class",
["./_base/lang","./_base/array","./dom"],function(a,i,l){function k(a){if("string"==typeof a||a instanceof String){if(a&&!m.test(a))return o[0]=a,o;a=a.split(m);a.length&&!a[0]&&a.shift();a.length&&!a[a.length-1]&&a.pop();return a}return!a?[]:i.filter(a,function(a){return a})}var j,m=/\s+/,o=[""],f={};return j={contains:function(a,c){return 0<=(" "+l.byId(a).className+" ").indexOf(" "+c+" ")},add:function(a,c){var a=l.byId(a),c=k(c),b=a.className,e,b=b?" "+b+" ":" ";e=b.length;for(var f=0,g=c.length,
h;f<g;++f)(h=c[f])&&0>b.indexOf(" "+h+" ")&&(b+=h+" ");e<b.length&&(a.className=b.substr(1,b.length-2))},remove:function(d,c){var d=l.byId(d),b;if(void 0!==c){c=k(c);b=" "+d.className+" ";for(var e=0,f=c.length;e<f;++e)b=b.replace(" "+c[e]+" "," ");b=a.trim(b)}else b="";d.className!=b&&(d.className=b)},replace:function(a,c,b){a=l.byId(a);f.className=a.className;j.remove(f,b);j.add(f,c);a.className!==f.className&&(a.className=f.className)},toggle:function(a,c,b){a=l.byId(a);if(void 0===b)for(var c=
k(c),e=0,f=c.length,g;e<f;++e)g=c[e],j[j.contains(a,g)?"remove":"add"](a,g);else j[b?"add":"remove"](a,c);return b}}})}}});define("frontend/layer/dom-common",[],1);