//>>built
require({cache:{"dijitive/Select":function(){define("dijitive/Select","dojo/_base/declare,dojo/_base/array,dojo/_base/lang,dijit/form/_FormSelectWidget,dijit/_Container,dojo/dom-attr,dojo/i18n,dojo/on,./Option,dojo/i18n!dijit/form/nls/validate".split(","),function(c,g,h,e,d,b,f,m,i){return c([e,d],{templateString:'<select name="${name}" data-dojo-attach-point="containerNode,focusNode"></select>',required:!1,message:"",postMixInProperties:function(){var b=f.getLocalization("dijit/form","validate",
this.lang);this._missingMsg=b?b.missingMessage:"Input required";this.inherited(arguments)},postCreate:function(){this.inherited(arguments);b.remove(this.domNode,"options");this.own(m(this.domNode,"change",h.hitch(this,function(){this._handleOnChange(this._getValueFromChildren());this.validate()})))},startup:function(){if(!this._started)this.store||this._loadChildren(),this._started=!0,this.validate()},_getValueFromChildren:function(){var b=[];if(!this.get("multiple"))return-1===this.domNode.selectedIndex?
null:this.domNode.options[this.domNode.selectedIndex].value;for(x=0;x<this.domNode.length;x+=1)if(this.domNode[x].selected)b[b.length]=this.domNode[x].value;return b},_updateSelection:function(){g.forEach(this.getChildren(),h.hitch(this,function(b){this._select(b)}))},_select:function(b){var c=!1,e=this.get("value");h.isArray(e)?g.forEach(e,function(e){e===b.get("value")&&(c=!0)}):e===b.get("value")&&(c=!0);b.set("selected",c)},_addOptionItem:function(b){this.addChild(new i({value:b.value,label:b.label,
disabled:b.disabled||!1}))},_setDisabledAttr:function(b){this.inherited(arguments);this.validate()},_setRequiredAttr:function(c){var e=c&&!this.get("disabled")?"true":"false";b.set(this.domNode,{required:e,"aria-required":e});this._set("required",c);this.validate()},validate:function(){if(this._started){var c=this.isValid();b.set(this.focusNode,"aria-invalid",c?"false":"true");this._set("message",c?"":this._missingMsg);return c}},isValid:function(){return this.disabled||!this.required||0===this.value||
!/^\s*$/.test(this.value||"")},_onFocus:function(){this.validate();this.inherited(arguments)},_onBlur:function(){this.inherited(arguments);this.validate()}})})},"dijit/form/_FormSelectWidget":function(){define("dijit/form/_FormSelectWidget","dojo/_base/array,dojo/_base/Deferred,dojo/aspect,dojo/data/util/sorter,dojo/_base/declare,dojo/dom,dojo/dom-class,dojo/_base/kernel,dojo/_base/lang,dojo/query,dojo/when,dojo/store/util/QueryResults,./_FormValueWidget".split(","),function(c,g,h,e,d,b,f,m,i,p,j,
l,r){return d("dijit.form._FormSelectWidget",r,{multiple:!1,options:null,store:null,query:null,queryOptions:null,labelAttr:"",onFetch:null,sortByLabel:!0,loadChildrenOnOpen:!1,onLoadDeferred:null,getOptions:function(a){var b=a,e=this.options||[],d=e.length;if(void 0===b)return e;if(i.isArray(b))return c.map(b,"return this.getOptions(item);",this);i.isObject(a)&&(c.some(this.options,function(a,c){return a===b||a.value&&a.value===b.value?(b=c,!0):!1})||(b=-1));if("string"==typeof b)for(a=0;a<d;a++)if(e[a].value===
b){b=a;break}return"number"==typeof b&&0<=b&&b<d?this.options[b]:null},addOption:function(a){i.isArray(a)||(a=[a]);c.forEach(a,function(a){a&&i.isObject(a)&&this.options.push(a)},this);this._loadChildren()},removeOption:function(a){i.isArray(a)||(a=[a]);a=this.getOptions(a);c.forEach(a,function(a){if(a)this.options=c.filter(this.options,function(b){return b.value!==a.value||b.label!==a.label}),this._removeOptionItem(a)},this);this._loadChildren()},updateOption:function(a){i.isArray(a)||(a=[a]);c.forEach(a,
function(a){var b=this.getOptions(a),c;if(b)for(c in a)b[c]=a[c]},this);this._loadChildren()},setStore:function(a,b,d){var f=this.store,d=d||{};if(f!==a){for(var m;m=this._notifyConnections.pop();)m.remove();if(!a.get&&(i.mixin(a,{_oldAPI:!0,get:function(a){var b=new g;this.fetchItemByIdentity({identity:a,onItem:function(a){b.resolve(a)},onError:function(a){b.reject(a)}});return b.promise},query:function(a,b){var c=new g(function(){e.abort&&e.abort()});c.total=new g;var e=this.fetch(i.mixin({query:a,
onBegin:function(a){c.total.resolve(a)},onComplete:function(a){c.resolve(a)},onError:function(a){c.reject(a)}},b));return new l(c)}}),a.getFeatures()["dojo.data.api.Notification"]))this._notifyConnections=[h.after(a,"onNew",i.hitch(this,"_onNewItem"),!0),h.after(a,"onDelete",i.hitch(this,"_onDeleteItem"),!0),h.after(a,"onSet",i.hitch(this,"_onSetItem"),!0)];this._set("store",a)}this.options&&this.options.length&&this.removeOption(this.options);this._queryRes&&this._queryRes.close&&this._queryRes.close();
d.query&&(this._set("query",d.query),this._set("queryOptions",d.queryOptions));if(a)this._loadingStore=!0,this.onLoadDeferred=new g,this._queryRes=a.query(this.query,this.queryOptions),j(this._queryRes,i.hitch(this,function(f){if(this.sortByLabel&&!d.sort&&f.length)if(f[0].getValue)f.sort(e.createSortFunction([{attribute:a.getLabelAttributes(f[0])[0]}],a));else{var h=this.labelAttr;f.sort(function(a,b){return a[h]>b[h]?1:b[h]>a[h]?-1:0})}d.onFetch&&(f=d.onFetch.call(this,f,d));c.forEach(f,function(a){this._addOptionForItem(a)},
this);this._queryRes.observe&&this._queryRes.observe(i.hitch(this,function(a,b,c){b==c?this._onSetItem(a):(-1!=b&&this._onDeleteItem(a),-1!=c&&this._onNewItem(a))}),!0);this._loadingStore=!1;this.set("value","_pendingValue"in this?this._pendingValue:b);delete this._pendingValue;this.loadChildrenOnOpen?this._pseudoLoadChildren(f):this._loadChildren();this.onLoadDeferred.resolve(!0);this.onSetStore()}),function(a){console.error("dijit.form.Select: "+a.toString());this.onLoadDeferred.reject(a)});return f},
_setValueAttr:function(a,b){this._onChangeActive||(b=null);if(this._loadingStore)this._pendingValue=a;else{var e=this.getOptions()||[];i.isArray(a)||(a=[a]);c.forEach(a,function(b,d){i.isObject(b)||(b+="");"string"===typeof b&&(a[d]=c.filter(e,function(a){return a.value===b})[0]||{value:"",label:""})},this);a=c.filter(a,function(a){return a&&a.value});if(!this.multiple&&(!a[0]||!a[0].value)&&e.length)a[0]=e[0];c.forEach(e,function(b){b.selected=c.some(a,function(a){return a.value===b.value})});var d=
c.map(a,function(a){return a.value}),f=c.map(a,function(a){return a.label});"undefined"==typeof d||"undefined"==typeof d[0]||(this._setDisplay(this.multiple?f:f[0]),this.inherited(arguments,[this.multiple?d:d[0],b]),this._updateSelection())}},_getDisplayedValueAttr:function(){var a=this.get("value");i.isArray(a)||(a=[a]);a=c.map(this.getOptions(a),function(a){return a&&"label"in a?a.label:a?a.value:null},this);return this.multiple?a:a[0]},_loadChildren:function(){this._loadingStore||(c.forEach(this._getChildren(),
function(a){a.destroyRecursive()}),c.forEach(this.options,this._addOptionItem,this),this._updateSelection())},_updateSelection:function(){this._set("value",this._getValueFromOpts());var a=this.value;i.isArray(a)||(a=[a]);a&&a[0]&&c.forEach(this._getChildren(),function(b){var e=c.some(a,function(a){return b.option&&a===b.option.value});f.toggle(b.domNode,this.baseClass.replace(/\s+|$/g,"SelectedOption "),e);b.domNode.setAttribute("aria-selected",e?"true":"false")},this)},_getValueFromOpts:function(){var a=
this.getOptions()||[];if(!this.multiple&&a.length){var b=c.filter(a,function(a){return a.selected})[0];if(b&&b.value)return b.value;a[0].selected=!0;return a[0].value}return this.multiple?c.map(c.filter(a,function(a){return a.selected}),function(a){return a.value})||[]:""},_onNewItem:function(a,b){(!b||!b.parent)&&this._addOptionForItem(a)},_onDeleteItem:function(a){this.removeOption(this.store.getIdentity(a))},_onSetItem:function(a){this.updateOption(this._getOptionObjForItem(a))},_getOptionObjForItem:function(a){var b=
this.store,c=this.labelAttr&&this.labelAttr in a?a[this.labelAttr]:b.getLabel(a);return{value:c?b.getIdentity(a):null,label:c,item:a}},_addOptionForItem:function(a){var b=this.store;b.isItemLoaded&&!b.isItemLoaded(a)?b.loadItem({item:a,onItem:function(a){this._addOptionForItem(a)},scope:this}):this.addOption(this._getOptionObjForItem(a))},constructor:function(a){this._oValue=(a||{}).value||null;this._notifyConnections=[]},buildRendering:function(){this.inherited(arguments);b.setSelectable(this.focusNode,
!1)},_fillContent:function(){if(!this.options)this.options=this.srcNodeRef?p("> *",this.srcNodeRef).map(function(a){return"separator"===a.getAttribute("type")?{value:"",label:"",selected:!1,disabled:!1}:{value:a.getAttribute("data-"+m._scopeName+"-value")||a.getAttribute("value"),label:""+a.innerHTML,selected:a.getAttribute("selected")||!1,disabled:a.getAttribute("disabled")||!1}},this):[];this.value?this.multiple&&"string"==typeof this.value&&this._set("value",this.value.split(",")):this._set("value",
this._getValueFromOpts())},postCreate:function(){this.inherited(arguments);this.connect(this,"onChange","_updateSelection");var a=this.store;if(a&&(a.getIdentity||a.getFeatures()["dojo.data.api.Identity"]))this.store=null,this.setStore(a,this._oValue)},startup:function(){this._loadChildren();this.inherited(arguments)},destroy:function(){for(var a;a=this._notifyConnections.pop();)a.remove();this._queryRes&&this._queryRes.close&&this._queryRes.close();this.inherited(arguments)},_addOptionItem:function(){},
_removeOptionItem:function(){},_setDisplay:function(){},_getChildren:function(){return[]},_getSelectedOptionsAttr:function(){return this.getOptions(this.get("value"))},_pseudoLoadChildren:function(){},onSetStore:function(){}})})},"dojo/data/util/sorter":function(){define("dojo/data/util/sorter",["../../_base/lang"],function(c){var g={};c.setObject("dojo.data.util.sorter",g);g.basicComparator=function(c,e){var d=-1;null===c&&(c=void 0);null===e&&(e=void 0);if(c==e)d=0;else if(c>e||null==c)d=1;return d};
g.createSortFunction=function(c,e){function d(b,a,c,e){return function(d,f){var i=e.getValue(d,b),h=e.getValue(f,b);return a*c(i,h)}}for(var b=[],f,m=e.comparatorMap,i=g.basicComparator,p=0;p<c.length;p++){f=c[p];var j=f.attribute;if(j){f=f.descending?-1:1;var l=i;m&&("string"!==typeof j&&"toString"in j&&(j=j.toString()),l=m[j]||i);b.push(d(j,f,l,e))}}return function(c,a){for(var e=0;e<b.length;){var d=b[e++](c,a);if(0!==d)return d}return 0}};return g})},"dojo/store/util/QueryResults":function(){define("dojo/store/util/QueryResults",
["../../_base/array","../../_base/lang","../../_base/Deferred"],function(c,g,h){var e=function(d){function b(b){d[b]||(d[b]=function(){var g=arguments;return h.when(d,function(d){Array.prototype.unshift.call(g,d);return e(c[b].apply(c,g))})})}if(!d)return d;d.then&&(d=g.delegate(d));b("forEach");b("filter");b("map");if(!d.total)d.total=h.when(d,function(b){return b.length});return d};g.setObject("dojo.store.util.QueryResults",e);return e})},"dijit/form/_FormValueWidget":function(){define("dijit/form/_FormValueWidget",
["dojo/_base/declare","dojo/sniff","./_FormWidget","./_FormValueMixin"],function(c,g,h,e){return c("dijit.form._FormValueWidget",[h,e],{_layoutHackIE7:function(){if(7==g("ie"))for(var c=this.domNode,b=c.parentNode,e=c.firstChild||c,h=e.style.filter,i=this;b&&0==b.clientHeight;)(function(){var c=i.connect(b,"onscroll",function(){i.disconnect(c);e.style.filter=(new Date).getMilliseconds();i.defer(function(){e.style.filter=h})})})(),b=b.parentNode}})})},"dijit/form/_FormValueMixin":function(){define("dijit/form/_FormValueMixin",
["dojo/_base/declare","dojo/dom-attr","dojo/keys","dojo/sniff","./_FormWidgetMixin"],function(c,g,h,e,d){return c("dijit.form._FormValueMixin",d,{readOnly:!1,_setReadOnlyAttr:function(b){g.set(this.focusNode,"readOnly",b);this.focusNode.setAttribute("aria-readonly",b);this._set("readOnly",b)},postCreate:function(){this.inherited(arguments);e("ie")&&this.connect(this.focusNode||this.domNode,"onkeydown",this._onKeyDown);if(void 0===this._resetValue)this._lastValueReported=this._resetValue=this.value},
_setValueAttr:function(b,c){this._handleOnChange(b,c)},_handleOnChange:function(b,c){this._set("value",b);this.inherited(arguments)},undo:function(){this._setValueAttr(this._lastValueReported,!1)},reset:function(){this._hasBeenBlurred=!1;this._setValueAttr(this._resetValue,!0)},_onKeyDown:function(b){if(b.keyCode==h.ESCAPE&&!b.ctrlKey&&!b.altKey&&!b.metaKey&&(9>e("ie")||e("ie")&&e("quirks"))){b.preventDefault();var c=b.srcElement,d=c.ownerDocument.createEventObject();d.keyCode=h.ESCAPE;d.shiftKey=
b.shiftKey;c.fireEvent("onkeypress",d)}}})})},"dijit/_Container":function(){define("dijit/_Container",["dojo/_base/array","dojo/_base/declare","dojo/dom-construct"],function(c,g,h){return g("dijit._Container",null,{buildRendering:function(){this.inherited(arguments);if(!this.containerNode)this.containerNode=this.domNode},addChild:function(c,d){var b=this.containerNode;if(d&&"number"==typeof d){var f=this.getChildren();if(f&&f.length>=d)b=f[d-1].domNode,d="after"}h.place(c.domNode,b,d);this._started&&
!c._started&&c.startup()},removeChild:function(c){"number"==typeof c&&(c=this.getChildren()[c]);if(c)(c=c.domNode)&&c.parentNode&&c.parentNode.removeChild(c)},hasChildren:function(){return 0<this.getChildren().length},_getSiblingOfChild:function(e,d){var b=this.getChildren(),f=c.indexOf(this.getChildren(),e);return b[f+d]},getIndexOfChild:function(e){return c.indexOf(this.getChildren(),e)}})})},"dojo/i18n":function(){define("dojo/i18n","./_base/kernel,require,./has,./_base/array,./_base/config,./_base/lang,./_base/xhr,./json,module".split(","),
function(c,g,h,e,d,b,f,m,i){h.add("dojo-preload-i18n-Api",1);var f=c.i18n={},p=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,j=function(a,b,c,d){for(var e=[c+d],b=b.split("-"),f="",h=0;h<b.length;h++)f+=(f?"-":"")+b[h],(!a||a[f])&&e.push(c+f+"/"+d);return e},l={},r=function(a,b,d){d=d?d.toLowerCase():c.locale;a=a.replace(/\./g,"/");b=b.replace(/\./g,"/");return/root/i.test(d)?a+"/nls/"+b:a+"/nls/"+d+"/"+b};c.getL10nName=function(a,b,c){return i.id+"!"+r(a,b,c)};var a=function(a,c,d,e,f,h){a([c],function(i){var g=
b.clone(i.root),s=j(!i._v1x&&i,f,d,e);a(s,function(){for(var a=1;a<s.length;a++)g=b.mixin(b.clone(g),arguments[a]);l[c+"/"+f]=g;h()})})},y=function(a){var c=d.extraLocale||[],c=b.isArray(c)?c:[c];c.push(a);return c},t=function(d,f,i){if(h("dojo-preload-i18n-Api")){var g=d.split("*"),j="preload"==g[1];j&&(l[d]||(l[d]=1,B(g[2],m.parse(g[3]),1,f)),i(1));if(!(g=j))q&&u.push([d,f,i]),g=q;if(g)return}var d=p.exec(d),k=d[1]+"/",n=d[5]||d[4],v=k+n,g=(d=d[5]&&d[4])||c.locale,s=v+"/"+g,d=d?[g]:y(g),C=d.length,
w=function(){--C||i(b.delegate(l[s]))};e.forEach(d,function(b){var c=v+"/"+b;h("dojo-preload-i18n-Api")&&o(c);l[c]?w():a(f,v,k,n,b,w)})};if(h("dojo-unit-tests"))var z=f.unitTests=[];h("dojo-preload-i18n-Api");var A=f.normalizeLocale=function(a){a=a?a.toLowerCase():c.locale;return"root"==a?"ROOT":a},q=0,u=[],B=f._preloadLocalizations=function(a,b,d,f){function h(a,b){f([a],b)}function i(a,b){for(var c=a.split("-");c.length;){if(b(c.join("-")))return;c.pop()}b("ROOT")}function j(c){c=A(c);i(c,function(c){if(0<=
e.indexOf(b,c)){var d=a.replace(/\./g,"/")+"_"+c;q++;h(d,function(a){for(var b in a)l[g.toAbsMid(b)+"/"+c]=a[b];for(--q;!q&&u.length;)t.apply(null,u.shift())});return!0}return!1})}f=f||g;j();e.forEach(c.config.extraLocale,j)},o=function(){},k={},n=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define = function(mid, factory){define.called = 1; __amdValue.result = factory || mid;},\t   require = function(){define.called = 1;};try{define.called = 0;eval(__bundle);if(define.called==1)return __amdValue;if((__checkForLegacyModules = __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
o=function(a){for(var b,d=a.split("/"),e=c.global[d[0]],f=1;e&&f<d.length-1;e=e[d[f++]]);e&&((b=e[d[f]])||(b=e[d[f].replace(/-/g,"_")]),b&&(l[a]=b));return b};f.getLocalization=function(a,b,c){var d,a=r(a,b,c);t(a,g,function(a){d=a});return d};h("dojo-unit-tests")&&z.push(function(a){a.register("tests.i18n.unit",function(a){var b;b=n("{prop:1}",o,"nonsense",k);a.is({prop:1},b);a.is(void 0,b[1]);b=n("({prop:1})",o,"nonsense",k);a.is({prop:1},b);a.is(void 0,b[1]);b=n("{'prop-x':1}",o,"nonsense",k);
a.is({"prop-x":1},b);a.is(void 0,b[1]);b=n("({'prop-x':1})",o,"nonsense",k);a.is({"prop-x":1},b);a.is(void 0,b[1]);b=n("define({'prop-x':1})",o,"nonsense",k);a.is(k,b);a.is({"prop-x":1},k.result);b=n("define('some/module', {'prop-x':1})",o,"nonsense",k);a.is(k,b);a.is({"prop-x":1},k.result);b=n("this is total nonsense and should throw an error",o,"nonsense",k);a.is(b instanceof Error,!0)})});return b.mixin(f,{dynamic:!0,normalize:function(a,b){return/^\./.test(a)?b(a):a},load:t,cache:l})})},"*now":function(c){c(['dojo/i18n!*preload*frontend/layer/nls/form-select*["ar","ca","cs","da","de","el","en-gb","en-us","es-es","fi-fi","fr-fr","he-il","hu","it-it","ja-jp","ko-kr","nl-nl","nb","pl","pt-br","pt-pt","ru","sk","sl","sv","th","tr","zh-tw","zh-cn","ROOT"]'])}}});
define("frontend/layer/form-select",[],1);