//>>built
require({cache:{"dijit/_Widget":function(){define("dijit/_Widget","dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/query,dojo/ready,./registry,./_WidgetBase,./_OnDijitClickMixin,./_FocusMixin,dojo/uacss,./hccss".split(","),function(g,n,m,i,l,o,j,a,h,f,b,c,e){function k(){}function w(a){return function(b,f,e,q){return b&&"string"==typeof f&&b[f]==k?b.on(f.substring(2).toLowerCase(),j.hitch(e,q)):a.apply(m,arguments)}}g.around(m,"connect",
w);o.connect&&g.around(o,"connect",w);g=i("dijit._Widget",[b,c,e],{onClick:k,onDblClick:k,onKeyDown:k,onKeyPress:k,onKeyUp:k,onMouseDown:k,onMouseMove:k,onMouseOut:k,onMouseOver:k,onMouseLeave:k,onMouseEnter:k,onMouseUp:k,constructor:function(a){this._toConnect={};for(var b in a)this[b]===k&&(this._toConnect[b.replace(/^on/,"").toLowerCase()]=a[b],delete a[b])},postCreate:function(){this.inherited(arguments);for(var a in this._toConnect)this.on(a,this._toConnect[a]);delete this._toConnect},on:function(a,
b){return this[this._onMap(a)]===k?m.connect(this.domNode,a.toLowerCase(),this,b):this.inherited(arguments)},_setFocusedAttr:function(a){this._focused=a;this._set("focused",a)},setAttribute:function(a,b){o.deprecated(this.declaredClass+"::setAttribute(attr, value) is deprecated. Use set() instead.","","2.0");this.set(a,b)},attr:function(a,b){if(n.isDebug){var f=arguments.callee._ach||(arguments.callee._ach={}),k=(arguments.callee.caller||"unknown caller").toString();f[k]||(o.deprecated(this.declaredClass+
"::attr() is deprecated. Use get() or set() instead, called from "+k,"","2.0"),f[k]=!0)}return 2<=arguments.length||"object"===typeof a?this.set.apply(this,arguments):this.get(a)},getDescendants:function(){o.deprecated(this.declaredClass+"::getDescendants() is deprecated. Use getChildren() instead.","","2.0");return this.containerNode?a("[widgetId]",this.containerNode).map(f.byNode):[]},_onShow:function(){this.onShow()},onShow:function(){},onHide:function(){},onClose:function(){return!0}});l("dijit-legacy-requires")&&
h(0,function(){require(["dijit/_base"])});return g})},"dijit/_OnDijitClickMixin":function(){define("dijit/_OnDijitClickMixin","dojo/on,dojo/_base/array,dojo/keys,dojo/_base/declare,dojo/has,dojo/_base/unload,dojo/_base/window,./a11yclick".split(","),function(g,n,m,i,l,o,j,a){g=i("dijit._OnDijitClickMixin",null,{connect:function(h,f,b){return this.inherited(arguments,[h,"ondijitclick"==f?a:f,b])}});g.a11yclick=a;return g})},"dijit/a11yclick":function(){define("dijit/a11yclick","dojo/on,dojo/_base/array,dojo/keys,dojo/_base/declare,dojo/has,dojo/_base/unload,dojo/_base/window".split(","),
function(g,n,m,i,l,o,j){function a(a){return(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&!a.ctrlKey&&!a.shiftKey&&!a.altKey&&!a.metaKey}var h=null;l("dom-addeventlistener")?j.doc.addEventListener("keydown",function(a){h=a.target},!0):function(){var a=function(a){h=a.srcElement};j.doc.attachEvent("onkeydown",a);o.addOnWindowUnload(function(){j.doc.detachEvent("onkeydown",a)})}();return function(f,b){if(/input|button/i.test(f.nodeName))return g(f,"click",b);var c=[g(f,"keydown",function(b){if(a(b))h=
b.target,b.preventDefault()}),g(f,"keyup",function(b){a(b)&&b.target==h&&(h=null,g.emit(b.target,"click",{cancelable:!0,bubbles:!0}))}),g(f,"click",function(a){b.call(this,a)})];if(l("touch")){var e;c.push(g(f,"touchend",function(a){var b=a.target;e=setTimeout(function(){e=null;g.emit(b,"click",{cancelable:!0,bubbles:!0})},600)}),g(f,"click",function(){e&&clearTimeout(e)}))}return{remove:function(){n.forEach(c,function(a){a.remove()});e&&(clearTimeout(e),e=null)}}}})},"dijit/_FocusMixin":function(){define("dijit/_FocusMixin",
["./focus","./_WidgetBase","dojo/_base/declare","dojo/_base/lang"],function(g,n,m,i){i.extend(n,{focused:!1,onFocus:function(){},onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()}});return m("dijit._FocusMixin",null,{_focusManager:g})})},"dijit/focus":function(){define("dijit/focus","dojo/aspect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-construct,dojo/Evented,dojo/_base/lang,dojo/on,dojo/domReady,dojo/sniff,dojo/Stateful,dojo/_base/unload,dojo/_base/window,dojo/window,./a11y,./registry,./main".split(","),
function(g,n,m,i,l,o,j,a,h,f,b,c,e,k,w,x,t){var s=new (n([b,o],{curNode:null,activeStack:[],constructor:function(){var a=j.hitch(this,function(a){m.isDescendant(this.curNode,a)&&this.set("curNode",null);m.isDescendant(this.prevNode,a)&&this.set("prevNode",null)});g.before(l,"empty",a);g.before(l,"destroy",a)},registerIframe:function(a){return this.registerWin(a.contentWindow,a)},registerWin:function(a,b){var d=this,e=function(a){d._justMouseDowned=!0;setTimeout(function(){d._justMouseDowned=!1},0);
if(!f("ie")||!a||!(a.srcElement&&null==a.srcElement.parentNode))d._onTouchNode(b||a.target||a.srcElement,"mouse")},c=f("ie")?a.document.documentElement:a.document;if(c){if(f("ie")){a.document.body.attachEvent("onmousedown",e);var k=function(a){var c=a.srcElement.tagName.toLowerCase();"#document"==c||"body"==c||(w.isTabNavigable(a.srcElement)?d._onFocusNode(b||a.srcElement):d._onTouchNode(b||a.srcElement))};c.attachEvent("onfocusin",k);var h=function(a){d._onBlurNode(b||a.srcElement)};c.attachEvent("onfocusout",
h);return{remove:function(){a.document.detachEvent("onmousedown",e);c.detachEvent("onfocusin",k);c.detachEvent("onfocusout",h);c=null}}}c.body.addEventListener("mousedown",e,!0);c.body.addEventListener("touchstart",e,!0);var g=function(a){d._onFocusNode(b||a.target)};c.addEventListener("focus",g,!0);var l=function(a){d._onBlurNode(b||a.target)};c.addEventListener("blur",l,!0);return{remove:function(){c.body.removeEventListener("mousedown",e,!0);c.body.removeEventListener("touchstart",e,!0);c.removeEventListener("focus",
g,!0);c.removeEventListener("blur",l,!0);c=null}}}},_onBlurNode:function(){this._clearFocusTimer&&clearTimeout(this._clearFocusTimer);this._clearFocusTimer=setTimeout(j.hitch(this,function(){this.set("prevNode",this.curNode);this.set("curNode",null)}),0);if(!this._justMouseDowned)this._clearActiveWidgetsTimer&&clearTimeout(this._clearActiveWidgetsTimer),this._clearActiveWidgetsTimer=setTimeout(j.hitch(this,function(){delete this._clearActiveWidgetsTimer;this._setStack([])}),0)},_onTouchNode:function(a,
b){this._clearActiveWidgetsTimer&&(clearTimeout(this._clearActiveWidgetsTimer),delete this._clearActiveWidgetsTimer);var d=[];try{for(;a;){var c=i.get(a,"dijitPopupParent");if(c)a=x.byId(c).domNode;else if(a.tagName&&"body"==a.tagName.toLowerCase()){if(a===e.body())break;a=k.get(a.ownerDocument).frameElement}else{var f=a.getAttribute&&a.getAttribute("widgetId"),h=f&&x.byId(f);h&&!("mouse"==b&&h.get("disabled"))&&d.unshift(f);a=a.parentNode}}}catch(g){}this._setStack(d,b)},_onFocusNode:function(a){a&&
9!=a.nodeType&&(this._clearFocusTimer&&(clearTimeout(this._clearFocusTimer),delete this._clearFocusTimer),this._onTouchNode(a),a!=this.curNode&&(this.set("prevNode",this.curNode),this.set("curNode",a)))},_setStack:function(a,b){var d=this.activeStack;this.set("activeStack",a);for(var c=0;c<Math.min(d.length,a.length)&&!(d[c]!=a[c]);c++);for(var e,f=d.length-1;f>=c;f--)if(e=x.byId(d[f]))e._hasBeenBlurred=!0,e.set("focused",!1),e._focusManager==this&&e._onBlur(b),this.emit("widget-blur",e,b);for(f=
c;f<a.length;f++)if(e=x.byId(a[f]))e.set("focused",!0),e._focusManager==this&&e._onFocus(b),this.emit("widget-focus",e,b)},focus:function(a){if(a)try{a.focus()}catch(b){}}}));h(function(){var a=s.registerWin(k.get(e.doc));f("ie")&&c.addOnWindowUnload(function(){a&&(a.remove(),a=null)})});t.focus=function(a){s.focus(a)};for(var r in s)/^_/.test(r)||(t.focus[r]="function"==typeof s[r]?j.hitch(s,r):s[r]);s.watch(function(a,b,d){t.focus[a]=d});return s})},"dojo/window":function(){define("dojo/window",
"./_base/lang,./sniff,./_base/window,./dom,./dom-geometry,./dom-style".split(","),function(g,n,m,i,l,o){var j={getBox:function(a){var a=a||m.doc,h="BackCompat"==a.compatMode?m.body(a):a.documentElement,f=l.docScroll(a);if(n("touch"))var b=j.get(a),a=b.innerWidth||h.clientWidth,h=b.innerHeight||h.clientHeight;else a=h.clientWidth,h=h.clientHeight;return{l:f.x,t:f.y,w:a,h:h}},get:function(a){if(n("ie")&&j!==document.parentWindow){a.parentWindow.execScript("document._parentWindow = window;","Javascript");
var h=a._parentWindow;a._parentWindow=null;return h}return a.parentWindow||a.defaultView},scrollIntoView:function(a,h){try{var a=i.byId(a),f=a.ownerDocument||m.doc,b=m.body(f),c=f.documentElement||b.parentNode,e=n("ie"),k=n("webkit");if((!n("mozilla")&&!e&&!k&&!n("opera")||a==b||a==c)&&"undefined"!=typeof a.scrollIntoView)a.scrollIntoView(!1);else{var g="BackCompat"==f.compatMode,j=9<=e&&"frameElement"in a.ownerDocument.parentWindow?0<c.clientHeight&&0<c.clientWidth&&(0==b.clientHeight||0==b.clientWidth||
b.clientHeight>c.clientHeight||b.clientWidth>c.clientWidth)?c:b:g?b:c,k=k?b:j,t=j.clientWidth,s=j.clientHeight,r=!l.isBodyLtr(f),q=h||l.position(a),p=a.parentNode,f=function(a){return 6>=e||e&&g?!1:"fixed"==o.get(a,"position").toLowerCase()};if(!f(a))for(;p;){p==b&&(p=k);var d=l.position(p),D=f(p);if(p==k){d.w=t;d.h=s;k==c&&e&&r&&(d.x+=k.offsetWidth-d.w);if(0>d.x||!e)d.x=0;if(0>d.y||!e)d.y=0}else{var v=l.getPadBorderExtents(p);d.w-=v.w;d.h-=v.h;d.x+=v.l;d.y+=v.t;var u=p.clientWidth,y=d.w-u;if(0<u&&
0<y)d.w=u,d.x+=r&&(e||p.clientLeft>v.l)?y:0;u=p.clientHeight;y=d.h-u;if(0<u&&0<y)d.h=u}if(D){if(0>d.y)d.h+=d.y,d.y=0;if(0>d.x)d.w+=d.x,d.x=0;if(d.y+d.h>s)d.h=s-d.y;if(d.x+d.w>t)d.w=t-d.x}var z=q.x-d.x,A=q.y-Math.max(d.y,0),C=z+q.w-d.w,E=A+q.h-d.h;if(0<C*z){var B=Math[0>z?"max":"min"](z,C);if(r&&(8==e&&!g||9<=e))B=-B;q.x+=p.scrollLeft;p.scrollLeft+=B;q.x-=p.scrollLeft}0<E*A&&(q.y+=p.scrollTop,p.scrollTop+=Math[0>A?"max":"min"](A,E),q.y-=p.scrollTop);p=p!=k&&!D&&p.parentNode}}}catch(F){console.error("scrollIntoView: "+
F),a.scrollIntoView(!1)}}};g.setObject("dojo.window",j);return j})},"dijit/a11y":function(){define("dijit/a11y","dojo/_base/array,dojo/_base/config,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-style,dojo/sniff,./main".split(","),function(g,n,m,i,l,o,j,a){var h=a._isElementShown=function(a){var c=o.get(a);return"hidden"!=c.visibility&&"collapsed"!=c.visibility&&"none"!=c.display&&"hidden"!=l.get(a,"type")};a.hasDefaultTabStop=function(a){switch(a.nodeName.toLowerCase()){case "a":return l.has(a,
"href");case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;case "iframe":var c;try{var e=a.contentDocument;if("designMode"in e&&"on"==e.designMode)return!0;c=e.body}catch(f){try{c=a.contentWindow.document.body}catch(g){return!1}}return c&&("true"==c.contentEditable||c.firstChild&&"true"==c.firstChild.contentEditable);default:return"true"==a.contentEditable}};var f=a.isTabNavigable=function(b){return l.get(b,"disabled")?!1:l.has(b,"tabIndex")?0<=l.get(b,"tabIndex"):
a.hasDefaultTabStop(b)};a._getTabNavigable=function(a){function c(a){return a&&"input"==a.tagName.toLowerCase()&&a.type&&"radio"==a.type.toLowerCase()&&a.name&&a.name.toLowerCase()}var e,g,i,n,m,o,r={},q=function(a){for(a=a.firstChild;a;a=a.nextSibling)if(!(1!=a.nodeType||j("ie")&&"HTML"!==a.scopeName||!h(a))){if(f(a)){var b=+l.get(a,"tabIndex");if(!l.has(a,"tabIndex")||0==b)e||(e=a),g=a;else if(0<b){if(!i||b<n)n=b,i=a;if(!m||b>=o)o=b,m=a}b=c(a);l.get(a,"checked")&&b&&(r[b]=a)}"SELECT"!=a.nodeName.toUpperCase()&&
q(a)}};h(a)&&q(a);return{first:r[c(e)]||e,last:r[c(g)]||g,lowest:r[c(i)]||i,highest:r[c(m)]||m}};a.getFirstInTabbingOrder=function(b,c){var e=a._getTabNavigable(i.byId(b,c));return e.lowest?e.lowest:e.first};a.getLastInTabbingOrder=function(b,c){var e=a._getTabNavigable(i.byId(b,c));return e.last?e.last:e.highest};return{hasDefaultTabStop:a.hasDefaultTabStop,isTabNavigable:a.isTabNavigable,_getTabNavigable:a._getTabNavigable,getFirstInTabbingOrder:a.getFirstInTabbingOrder,getLastInTabbingOrder:a.getLastInTabbingOrder}})},
"dojo/uacss":function(){define("dojo/uacss",["./dom-geometry","./_base/lang","./domReady","./sniff","./_base/window"],function(g,n,m,i,l){var o=l.doc.documentElement,l=i("ie"),j=i("opera"),a=Math.floor,h=i("ff"),f=g.boxModel.replace(/-/,""),j={dj_quirks:i("quirks"),dj_opera:j,dj_khtml:i("khtml"),dj_webkit:i("webkit"),dj_safari:i("safari"),dj_chrome:i("chrome"),dj_gecko:i("mozilla")};if(l)j.dj_ie=!0,j["dj_ie"+a(l)]=!0,j.dj_iequirks=i("quirks");h&&(j["dj_ff"+a(h)]=!0);j["dj_"+f]=!0;var b="",c;for(c in j)j[c]&&
(b+=c+" ");o.className=n.trim(o.className+" "+b);m(function(){if(!g.isBodyLtr()){var a="dj_rtl dijitRtl "+b.replace(/ /g,"-rtl ");o.className=n.trim(o.className+" "+a+"dj_rtl dijitRtl "+b.replace(/ /g,"-rtl "))}});return i})},"dijit/hccss":function(){define("dijit/hccss",["dojo/dom-class","dojo/hccss","dojo/domReady","dojo/_base/window"],function(g,n,m,i){m(function(){n("highcontrast")&&g.add(i.body(),"dijit_a11y")});return n})},"dojo/hccss":function(){define("dojo/hccss","require,./_base/config,./dom-class,./dom-construct,./dom-style,./has,./domReady,./_base/window".split(","),
function(g,n,m,i,l,o,j,a){o.add("highcontrast",function(){var h=a.doc.createElement("div");h.style.cssText="border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;background-image: url("+(n.blankGif||g.toUrl("./resources/blank.gif"))+");";a.body().appendChild(h);var f=l.getComputedStyle(h),b=f.backgroundImage,f=f.borderTopColor==f.borderRightColor||b&&("none"==b||"url(invalid-url:)"==b);i.destroy(h);return f});j(function(){o("highcontrast")&&m.add(a.body(),"dj_a11y")});
return o})}}});define("frontend/layer/widget-extra",[],1);