//>>built
require({cache:{"dijitive/Button":function(){define("dijitive/Button",["dojo/_base/declare","dojo/_base/lang","dijit/form/_FormWidget","dijit/form/_ButtonMixin"],function(e,c,d,a){return e([d,a],{templateString:'<button ${!nameAttrSetting} type="${type}" value="${value}" data-dojo-attach-point="focusNode,valueNode,labelNode" data-dojo-attach-event="onclick:_onClick"></button>',_fillContent:function(a){if(a&&(!this.params||!("label"in this.params)))if(a=c.trim(a.innerHTML))this.label=a}})})},"dijit/form/_FormWidget":function(){define("dijit/form/_FormWidget",
"dojo/_base/declare,dojo/has,dojo/_base/kernel,dojo/ready,../_Widget,../_CssStateMixin,../_TemplatedMixin,./_FormWidgetMixin".split(","),function(e,c,d,a,b,h,i,f){c("dijit-legacy-requires")&&a(0,function(){require(["dijit/form/_FormValueWidget"])});return e("dijit.form._FormWidget",[b,i,h,f],{setDisabled:function(a){d.deprecated("setDisabled("+a+") is deprecated. Use set('disabled',"+a+") instead.","","2.0");this.set("disabled",a)},setValue:function(a){d.deprecated("dijit.form._FormWidget:setValue("+
a+") is deprecated.  Use set('value',"+a+") instead.","","2.0");this.set("value",a)},getValue:function(){d.deprecated(this.declaredClass+"::getValue() is deprecated. Use get('value') instead.","","2.0");return this.get("value")},postMixInProperties:function(){this.nameAttrSetting=this.name?'name="'+this.name.replace(/"/g,"&quot;")+'"':"";this.inherited(arguments)},_setTypeAttr:null})})},"dijit/_CssStateMixin":function(){define("dijit/_CssStateMixin","dojo/_base/array,dojo/_base/declare,dojo/dom,dojo/dom-class,dojo/has,dojo/_base/lang,dojo/on,dojo/domReady,dojo/_base/window,./registry".split(","),
function(e,c,d,a,b,h,i,f,j,g){c=c("dijit._CssStateMixin",[],{cssStateNodes:{},hovering:!1,active:!1,_applyAttributes:function(){this.inherited(arguments);e.forEach("disabled,readOnly,checked,selected,focused,state,hovering,active,_opened".split(","),function(a){this.watch(a,h.hitch(this,"_setStateClass"))},this);for(var a in this.cssStateNodes)this._trackMouseState(this[a],this.cssStateNodes[a]);this._trackMouseState(this.domNode,this.baseClass);this._setStateClass()},_cssMouseEvent:function(a){if(!this.disabled)switch(a.type){case "mouseover":this._set("hovering",
!0);this._set("active",this._mouseDown);break;case "mouseout":this._set("hovering",!1);this._set("active",!1);break;case "mousedown":case "touchstart":this._set("active",!0);break;case "mouseup":case "touchend":this._set("active",!1)}},_setStateClass:function(){function a(g){b=b.concat(e.map(b,function(a){return a+g}),"dijit"+g)}var b=this.baseClass.split(" ");this.isLeftToRight()||a("Rtl");var g="mixed"==this.checked?"Mixed":this.checked?"Checked":"";this.checked&&a(g);this.state&&a(this.state);
this.selected&&a("Selected");this._opened&&a("Opened");this.disabled?a("Disabled"):this.readOnly?a("ReadOnly"):this.active?a("Active"):this.hovering&&a("Hover");this.focused&&a("Focused");var g=this.stateNode||this.domNode,d={};e.forEach(g.className.split(" "),function(a){d[a]=!0});"_stateClasses"in this&&e.forEach(this._stateClasses,function(a){delete d[a]});e.forEach(b,function(a){d[a]=!0});var c=[],f;for(f in d)c.push(f);g.className=c.join(" ");this._stateClasses=b},_subnodeCssMouseEvent:function(b,
g,d){function c(d){a.toggle(b,g+"Active",d)}if(!this.disabled&&!this.readOnly)switch(d.type){case "mouseover":a.toggle(b,g+"Hover",!0);break;case "mouseout":a.toggle(b,g+"Hover",!1);c(!1);break;case "mousedown":case "touchstart":c(!0);break;case "mouseup":case "touchend":c(!1);break;case "focus":case "focusin":a.toggle(b,g+"Focused",!0);break;case "blur":case "focusout":a.toggle(b,g+"Focused",!1)}},_trackMouseState:function(a,b){a._cssState=b}});f(function(){function a(b){if(!d.isDescendant(b.relatedTarget,
b.target))for(var c=b.target;c&&c!=b.relatedTarget;c=c.parentNode)if(c._cssState){var f=g.getEnclosingWidget(c);f&&(c==f.domNode?f._cssMouseEvent(b):f._subnodeCssMouseEvent(c,c._cssState,b))}}function c(b){b.target=b.srcElement;a(b)}var f=j.body(),h=(b("touch")?[]:["mouseover","mouseout"]).concat(["mousedown","touchstart","mouseup","touchend"]);e.forEach(h,function(b){f.addEventListener?f.addEventListener(b,a,!0):f.attachEvent("on"+b,c)});i(f,"focusin, focusout",function(a){var b=a.target;b._cssState&&
!b.getAttribute("widgetId")&&g.getEnclosingWidget(b)._subnodeCssMouseEvent(b,b._cssState,a)})});return c})},"dijit/form/_FormWidgetMixin":function(){define("dijit/form/_FormWidgetMixin","dojo/_base/array,dojo/_base/declare,dojo/dom-attr,dojo/dom-style,dojo/_base/lang,dojo/mouse,dojo/sniff,dojo/window,../a11y".split(","),function(e,c,d,a,b,h,i,f,j){return c("dijit.form._FormWidgetMixin",null,{name:"",alt:"",value:"",type:"text",tabIndex:"0",_setTabIndexAttr:"focusNode",disabled:!1,intermediateChanges:!1,
scrollOnFocus:!0,_setIdAttr:"focusNode",_setDisabledAttr:function(a){this._set("disabled",a);d.set(this.focusNode,"disabled",a);this.valueNode&&d.set(this.valueNode,"disabled",a);this.focusNode.setAttribute("aria-disabled",a?"true":"false");a?(this._set("hovering",!1),this._set("active",!1),a="tabIndex"in this.attributeMap?this.attributeMap.tabIndex:"_setTabIndexAttr"in this?this._setTabIndexAttr:"focusNode",e.forEach(b.isArray(a)?a:[a],function(a){a=this[a];i("webkit")||j.hasDefaultTabStop(a)?a.setAttribute("tabIndex",
"-1"):a.removeAttribute("tabIndex")},this)):""!=this.tabIndex&&this.set("tabIndex",this.tabIndex)},_onFocus:function(a){if("mouse"==a&&this.isFocusable())var b=this.connect(this.focusNode,"onfocus",function(){this.disconnect(c);this.disconnect(b)}),c=this.connect(this.ownerDocumentBody,"onmouseup",function(){this.disconnect(c);this.disconnect(b);this.focused&&this.focus()});this.scrollOnFocus&&this.defer(function(){f.scrollIntoView(this.domNode)});this.inherited(arguments)},isFocusable:function(){return!this.disabled&&
this.focusNode&&"none"!=a.get(this.domNode,"display")},focus:function(){if(!this.disabled&&this.focusNode.focus)try{this.focusNode.focus()}catch(a){}},compare:function(a,b){return"number"==typeof a&&"number"==typeof b?isNaN(a)&&isNaN(b)?0:a-b:a>b?1:a<b?-1:0},onChange:function(){},_onChangeActive:!1,_handleOnChange:function(a,b){if(void 0==this._lastValueReported&&(null===b||!this._onChangeActive))this._resetValue=this._lastValueReported=a;this._pendingOnChange=this._pendingOnChange||typeof a!=typeof this._lastValueReported||
0!=this.compare(a,this._lastValueReported);if((this.intermediateChanges||b||void 0===b)&&this._pendingOnChange)if(this._lastValueReported=a,this._pendingOnChange=!1,this._onChangeActive)this._onChangeHandle&&this._onChangeHandle.remove(),this._onChangeHandle=this.defer(function(){this._onChangeHandle=null;this.onChange(a)})},create:function(){this.inherited(arguments);this._onChangeActive=!0},destroy:function(){this._onChangeHandle&&(this._onChangeHandle.remove(),this.onChange(this._lastValueReported));
this.inherited(arguments)}})})},"dijit/form/_ButtonMixin":function(){define("dijit/form/_ButtonMixin",["dojo/_base/declare","dojo/dom","dojo/_base/event","../registry"],function(e,c,d,a){return e("dijit.form._ButtonMixin",null,{label:"",type:"button",_onClick:function(b){if(this.disabled)return d.stop(b),!1;var c=!1===this.onClick(b);if(!c&&"submit"==this.type&&!(this.valueNode||this.focusNode).form)for(var e=this.domNode;e.parentNode;e=e.parentNode){var f=a.byNode(e);if(f&&"function"==typeof f._onSubmit){f._onSubmit(b);
c=!0;break}}c&&b.preventDefault();return!c},postCreate:function(){this.inherited(arguments);c.setSelectable(this.focusNode,!1)},onClick:function(){return!0},_setLabelAttr:function(a){this._set("label",a);var c=this.containerNode||this.focusNode;c.innerHTML=a;this.textDir&&this.applyTextDir(c)}})})},"dijitive/Checkbox":function(){define("dijitive/Checkbox","dojo/_base/declare,dojo/_base/lang,dojo/dom-attr,dojo/on,dijit/form/_FormWidget,dijit/form/_CheckBoxMixin".split(","),function(e,c,d,a,b,h){return e([b,
h],{templateString:'<input ${!nameAttrSetting} type="${type}" ${checkedAttrSetting} data-dojo-attach-point="containerNode,focusNode" />',postMixInProperties:function(){this.inherited(arguments);this.checkedAttrSetting=this.checked?"checked":""},postCreate:function(){this.own(a(this.domNode,"change",c.hitch(this,function(){this.set("checked",this.domNode.checked)})))},_setCheckedAttr:function(a){this.get("readOnly");a?(d.set(this.domNode,"checked","checked"),d.set(this.domNode,"aria-checked","true")):
(d.set(this.domNode,"checked",""),d.set(this.domNode,"aria-checked","false"));this._set("checked",a);this._handleOnChange(a)},_getValueAttr:function(){return this.checked?this.value:!1}})})},"dijit/form/_CheckBoxMixin":function(){define("dijit/form/_CheckBoxMixin",["dojo/_base/declare","dojo/dom-attr","dojo/_base/event"],function(e,c,d){return e("dijit.form._CheckBoxMixin",null,{type:"checkbox",value:"on",readOnly:!1,_aria_attr:"aria-checked",_setReadOnlyAttr:function(a){this._set("readOnly",a);c.set(this.focusNode,
"readOnly",a);this.focusNode.setAttribute("aria-readonly",a)},_setLabelAttr:void 0,_getSubmitValue:function(a){return!a&&0!==a?"on":a},_setValueAttr:function(a){a=this._getSubmitValue(a);this._set("value",a);c.set(this.focusNode,"value",a)},reset:function(){this.inherited(arguments);this._set("value",this.params.value||"on");c.set(this.focusNode,"value",this.value)},_onClick:function(a){return this.readOnly?(d.stop(a),!1):this.inherited(arguments)}})})},"dijitive/Option":function(){define("dijitive/Option",
["dojo/_base/declare","dijit/_WidgetBase","dijit/_TemplatedMixin","dojo/dom-attr"],function(e,c,d,a){return e([c,d],{templateString:"<option></option>",value:"",label:"",selected:!1,disabled:!1,xxx:"asdf",_setValueAttr:function(b){a.set(this.domNode,"value",b);this._set("value",b)},_setLabelAttr:function(a){this.domNode.innerHTML=a;this._set("label",a)},_setSelectedAttr:function(b){b&&!this.get("disabled")?a.set(this.domNode,"selected","selected"):a.remove(this.domNode,"selected");this._set("selected",
b)},_setDisabledAttr:function(b){b||this.get("disabled")?a.set(this.domNode,"disabled","true"):a.remove(this.domNode,"disabled");this._set("disabled",b)}})})},"dijitive/Radio":function(){define("dijitive/Radio",["dojo/_base/declare","dijitive/Checkbox","dijit/form/_RadioButtonMixin"],function(e,c,d){return e([c,d],{})})},"dijit/form/_RadioButtonMixin":function(){define("dijit/form/_RadioButtonMixin","dojo/_base/array,dojo/_base/declare,dojo/dom-attr,dojo/_base/event,dojo/_base/lang,dojo/query,../registry".split(","),
function(e,c,d,a,b,h,i){return c("dijit.form._RadioButtonMixin",null,{type:"radio",_getRelatedWidgets:function(){var a=[];h("input[type=radio]",this.focusNode.form||this.ownerDocument).forEach(b.hitch(this,function(b){b.name==this.name&&b.form==this.focusNode.form&&(b=i.getEnclosingWidget(b))&&a.push(b)}));return a},_setCheckedAttr:function(a){this.inherited(arguments);this._created&&a&&e.forEach(this._getRelatedWidgets(),b.hitch(this,function(a){a!=this&&a.checked&&a.set("checked",!1)}))},_getSubmitValue:function(a){return null===
a?"on":a},_onClick:function(c){if(this.checked||this.disabled)return a.stop(c),!1;return this.readOnly?(a.stop(c),e.forEach(this._getRelatedWidgets(),b.hitch(this,function(a){d.set(this.focusNode||this.domNode,"checked",a.checked)})),!1):this.inherited(arguments)}})})}}});define("frontend/layer/form-click",[],1);