//>>built
require({cache:{"dojo/Deferred":function(){define("dojo/Deferred",["./has","./_base/lang","./errors/CancelError","./promise/Promise","./promise/instrumentation"],function(g,j,b,h,c){var d=Object.freeze||function(){},a=function(a,e,n,m,b){2===e&&k.instrumentRejected&&0===a.length&&k.instrumentRejected(n,!1,m,b);for(b=0;b<a.length;b++)f(a[b],e,n,m)},f=function(a,e,n,b){var f=a[e],c=a.deferred;if(f)try{var d=f(n);if(0===e)"undefined"!==typeof d&&l(c,e,d);else{if(d&&"function"===typeof d.then){a.cancel=
d.cancel;d.then(i(c,1),i(c,2),i(c,0));return}l(c,1,d)}}catch(h){l(c,2,h)}else l(c,e,n);2===e&&k.instrumentRejected&&k.instrumentRejected(n,!!f,b,c.promise)},i=function(a,e){return function(b){l(a,e,b)}},l=function(a,e,b){if(!a.isCanceled())switch(e){case 0:a.progress(b);break;case 1:a.resolve(b);break;case 2:a.reject(b)}},k=function(c){var e=this.promise=new h,n=this,m,i,j,g=!1,l=[];Error.captureStackTrace&&(Error.captureStackTrace(n,k),Error.captureStackTrace(e,k));this.isResolved=e.isResolved=function(){return 1===
m};this.isRejected=e.isRejected=function(){return 2===m};this.isFulfilled=e.isFulfilled=function(){return!!m};this.isCanceled=e.isCanceled=function(){return g};this.progress=function(b,c){if(m){if(!0===c)throw Error("This deferred has already been fulfilled.");return e}a(l,0,b,null,n);return e};this.resolve=function(b,c){if(m){if(!0===c)throw Error("This deferred has already been fulfilled.");return e}a(l,m=1,i=b,null,n);l=null;return e};var o=this.reject=function(b,c){if(m){if(!0===c)throw Error("This deferred has already been fulfilled.");
return e}Error.captureStackTrace&&Error.captureStackTrace(j={},o);a(l,m=2,i=b,j,n);l=null;return e};this.then=e.then=function(a,b,c){var d=[c,a,b];d.cancel=e.cancel;d.deferred=new k(function(a){return d.cancel&&d.cancel(a)});m&&!l?f(d,m,i,j):l.push(d);return d.deferred.promise};this.cancel=e.cancel=function(a,e){if(m){if(!0===e)throw Error("This deferred has already been fulfilled.");}else{if(c)var d=c(a),a="undefined"===typeof d?a:d;g=!0;if(m){if(2===m&&i===a)return a}else return"undefined"===typeof a&&
(a=new b),o(a),a}};d(e)};k.prototype.toString=function(){return"[object Deferred]"};c&&c(k);return k})},"dojo/errors/CancelError":function(){define("dojo/errors/CancelError",["./create"],function(g){return g("CancelError",null,null,{dojoType:"cancel"})})},"dojo/errors/create":function(){define("dojo/errors/create",["../_base/lang"],function(g){return function(j,b,h,c){var h=h||Error,d=function(a){if(h===Error){Error.captureStackTrace&&Error.captureStackTrace(this,d);var c=Error.call(this,a),i;for(i in c)c.hasOwnProperty(i)&&
(this[i]=c[i]);this.message=a;this.stack=c.stack}else h.apply(this,arguments);b&&b.apply(this,arguments)};d.prototype=g.delegate(h.prototype,c);d.prototype.name=j;return d.prototype.constructor=d}})},"dojo/promise/Promise":function(){define("dojo/promise/Promise",["../_base/lang"],function(g){function j(){throw new TypeError("abstract");}return g.extend(function(){},{then:function(){j()},cancel:function(){j()},isResolved:function(){j()},isRejected:function(){j()},isFulfilled:function(){j()},isCanceled:function(){j()},
always:function(b){return this.then(b,b)},otherwise:function(b){return this.then(null,b)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},"dojo/promise/instrumentation":function(){define("dojo/promise/instrumentation",["./tracer","../has","../_base/lang","../_base/array"],function(g,j,b,h){function c(a,c,b){var d="";a&&a.stack&&(d+=a.stack);c&&c.stack&&(d+="\n    ----------------------------------------\n    rejected"+c.stack.split("\n").slice(1).join("\n").replace(/^\s+/,
" "));b&&b.stack&&(d+="\n    ----------------------------------------\n"+b.stack);console.error(a,d)}function d(a,b,d,f){b||c(a,d,f)}function a(a,b,c,d){b?h.some(i,function(b,c){if(b.error===a)return i.splice(c,1),!0}):h.some(i,function(b){return b.error===a})||i.push({error:a,rejection:c,deferred:d,timestamp:(new Date).getTime()});l||(l=setTimeout(f,k))}function f(){var a=(new Date).getTime(),b=a-k;i=h.filter(i,function(a){return a.timestamp<b?(c(a.error,a.rejection,a.deferred),!1):!0});i.length&&
(l=setTimeout(f,i[0].timestamp+k-a))}var i=[],l=!1,k=1E3;return function(c){var e=j("config-useDeferredInstrumentation");if(e){g.on("resolved",b.hitch(console,"log","resolved"));g.on("rejected",b.hitch(console,"log","rejected"));g.on("progress",b.hitch(console,"log","progress"));var f=[];"string"===typeof e&&(f=e.split(","),e=f.shift());if("report-rejections"===e)c.instrumentRejected=d;else if("report-unhandled-rejections"===e||!0===e||1===e)c.instrumentRejected=a,k=parseInt(f[0],10)||k;else throw Error("Unsupported instrumentation usage <"+
e+">");}}})},"dojo/promise/tracer":function(){define("dojo/promise/tracer",["../_base/lang","./Promise","../Evented"],function(g,j,b){function h(a){setTimeout(function(){d.apply(c,a)},0)}var c=new b,d=c.emit;c.emit=null;j.prototype.trace=function(){var a=g._toArray(arguments);this.then(function(b){h(["resolved",b].concat(a))},function(b){h(["rejected",b].concat(a))},function(b){h(["progress",b].concat(a))});return this};j.prototype.traceRejected=function(){var a=g._toArray(arguments);this.otherwise(function(b){h(["rejected",
b].concat(a))});return this};return c})},"dojo/promise/all":function(){define("dojo/promise/all",["../_base/array","../Deferred","../when"],function(g,j,b){var h=g.some;return function(c){var d,a;c instanceof Array?a=c:c&&"object"===typeof c&&(d=c);var f,i=[];if(d){a=[];for(var g in d)Object.hasOwnProperty.call(d,g)&&(i.push(g),a.push(d[g]));f={}}else a&&(f=[]);if(!a||!a.length)return(new j).resolve(f);var k=new j;k.promise.always(function(){f=i=null});var p=a.length;h(a,function(a,c){d||i.push(c);
b(a,function(a){k.isFulfilled()||(f[i[c]]=a,0===--p&&k.resolve(f))},k.reject);return k.isFulfilled()});return k.promise}})},"dojo/when":function(){define("dojo/when",["./Deferred","./promise/Promise"],function(g,j){return function(b,h,c,d){var a=b&&"function"===typeof b.then,f=a&&b instanceof j;if(a){if(!f)a=new g(b.cancel),b.then(a.resolve,a.reject,a.progress),b=a.promise}else return h?h(b):(new g).resolve(b);return h||c||d?b.then(h,c,d):b}})},"dojo/promise/first":function(){define("dojo/promise/first",
["../_base/array","../Deferred","../when"],function(g,j,b){var h=g.forEach;return function(c){var d;if(c instanceof Array)d=c;else if(c&&"object"===typeof c){d=[];for(var a in c)Object.hasOwnProperty.call(c,a)&&d.push(c[a])}if(!d||!d.length)return(new j).resolve();var f=new j;h(d,function(a){b(a,f.resolve,f.reject)});return f.promise}})}}});define("frontend/layer/promise",[],1);