//>>built
require({cache:{"dijit/_TemplatedMixin":function(){define("dijit/_TemplatedMixin","dojo/_base/lang,dojo/touch,./_WidgetBase,dojo/string,dojo/cache,dojo/_base/array,dojo/_base/declare,dojo/dom-construct,dojo/sniff,dojo/_base/unload".split(","),function(i,h,g,f,a,c,e,k,d,b){var l=e("dijit._TemplatedMixin",null,{templateString:null,templatePath:null,_skipNodeCache:!1,_earlyTemplatedStartup:!1,constructor:function(){this._attachPoints=[];this._attachEvents=[]},_stringRepl:function(a){var j=this.declaredClass,
d=this;return f.substitute(a,this,function(a,b){"!"==b.charAt(0)&&(a=i.getObject(b.substr(1),!1,d));if("undefined"==typeof a)throw Error(j+" template:"+b);return null==a?"":"!"==b.charAt(0)?a:a.toString().replace(/"/g,"&quot;")},this)},buildRendering:function(){if(!this.templateString)this.templateString=a(this.templatePath,{sanitize:!0});var b=l.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),j;if(i.isString(b)){if(j=k.toDom(this._stringRepl(b),this.ownerDocument),1!=
j.nodeType)throw Error("Invalid template: "+b);}else j=b.cloneNode(!0);this.domNode=j;this.inherited(arguments);this._attachTemplateNodes(j,function(a,b){return a.getAttribute(b)});this._beforeFillContent();this._fillContent(this.srcNodeRef)},_beforeFillContent:function(){},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)},_attachTemplateNodes:function(a,b){for(var d=i.isArray(a)?a:a.all||a.getElementsByTagName("*"),c=i.isArray(a)?0:-1;0>
c||d[c];c++){var e=-1==c?a:d[c];if(!this.widgetsInTemplate||!b(e,"dojoType")&&!b(e,"data-dojo-type")){var f=b(e,"dojoAttachPoint")||b(e,"data-dojo-attach-point");if(f)for(var l=f.split(/\s*,\s*/);f=l.shift();)i.isArray(this[f])?this[f].push(e):this[f]=e,this._attachPoints.push(f);if(f=b(e,"dojoAttachEvent")||b(e,"data-dojo-attach-event"))for(var l=f.split(/\s*,\s*/),g=i.trim;f=l.shift();)if(f){var k=null;-1!=f.indexOf(":")?(k=f.split(":"),f=g(k[0]),k=g(k[1])):f=g(f);k||(k=f);this._attachEvents.push(this.connect(e,
h[f]||f,k))}}}},destroyRendering:function(){c.forEach(this._attachPoints,function(a){delete this[a]},this);this._attachPoints=[];c.forEach(this._attachEvents,this.disconnect,this);this._attachEvents=[];this.inherited(arguments)}});l._templateCache={};l.getCachedTemplate=function(a,b,d){var e=l._templateCache,c=a,g=e[c];if(g){try{if(!g.ownerDocument||g.ownerDocument==(d||document))return g}catch(i){}k.destroy(g)}a=f.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return e[c]=a;b=k.toDom(a,d);if(1!=b.nodeType)throw Error("Invalid template: "+
a);return e[c]=b};d("ie")&&b.addOnWindowUnload(function(){var a=l._templateCache,b;for(b in a){var d=a[b];"object"==typeof d&&k.destroy(d);delete a[b]}});i.extend(g,{dojoAttachEvent:"",dojoAttachPoint:""});return l})},"dojo/touch":function(){define("dojo/touch","./_base/kernel,./_base/lang,./aspect,./dom,./on,./has,./mouse,./domReady,./_base/window".split(","),function(i,h,g,f,a,c,e,k,d){function b(b){return function(d,e){return a(d,b,e)}}var g=c("touch"),l=!1;c("ios")&&(c=navigator.userAgent.match(/OS ([\d_]+)/)?
RegExp.$1:"1",l=5>parseFloat(c.replace(/_/,".").replace(/_/g,"")));var p,j;g&&(k(function(){j=d.body();d.doc.addEventListener("touchstart",function(b){var d=j;j=b.target;a.emit(d,"dojotouchout",{target:d,relatedTarget:j,bubbles:!0});a.emit(j,"dojotouchover",{target:j,relatedTarget:d,bubbles:!0})},!0);a(d.doc,"touchmove",function(b){if((b=d.doc.elementFromPoint(b.pageX-(l?0:d.global.pageXOffset),b.pageY-(l?0:d.global.pageYOffset)))&&j!==b)a.emit(j,"dojotouchout",{target:j,relatedTarget:b,bubbles:!0}),
a.emit(b,"dojotouchover",{target:b,relatedTarget:j,bubbles:!0}),j=b})}),p=function(b,e){return a(d.doc,"touchmove",function(a){(b===d.doc||f.isDescendant(j,b))&&e.call(this,h.mixin({},a,{target:j,touches:a.touches,preventDefault:function(){a.preventDefault()},stopPropagation:function(){a.stopPropagation()}}))})});e={press:b(g?"touchstart":"mousedown"),move:g?p:b("mousemove"),release:b(g?"touchend":"mouseup"),cancel:g?b("touchcancel"):e.leave,over:b(g?"dojotouchover":"mouseover"),out:b(g?"dojotouchout":
"mouseout"),enter:e._eventHandler(g?"dojotouchover":"mouseover"),leave:e._eventHandler(g?"dojotouchout":"mouseout")};return i.touch=e})},"dijit/_WidgetBase":function(){define("dijit/_WidgetBase","require,dojo/_base/array,dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-class,dojo/dom-construct,dojo/dom-geometry,dojo/dom-style,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/on,dojo/ready,dojo/Stateful,dojo/topic,dojo/_base/window,./Destroyable,./registry".split(","),
function(i,h,g,f,a,c,e,k,d,b,l,p,j,v,m,n,q,r,w,s,x,o){function t(a){return function(b){k[b?"set":"remove"](this.domNode,a,b);this._set(a,b)}}j.add("dijit-legacy-requires",!v.isAsync);j("dijit-legacy-requires")&&q(0,function(){i(["dijit/_base/manager"])});var u={};return c("dijit._WidgetBase",[r,x],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:t("lang"),dir:"",_setDirAttr:t("dir"),textDir:"","class":"",_setClassAttr:{node:"domNode",type:"class"},style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,
domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:f.blankGif||i.toUrl("dojo/resources/blank.gif"),postscript:function(a,b){this.create(a,b)},create:function(a,b){this.srcNodeRef=e.byId(b);this._connects=[];this._supportingWidgets=[];if(this.srcNodeRef&&"string"==typeof this.srcNodeRef.id)this.id=this.srcNodeRef.id;if(a)this.params=a,m.mixin(this,a);this.postMixInProperties();if(!this.id)this.id=o.getUniqueId(this.declaredClass.replace(/\./g,
"_")),this.params&&delete this.params.id;this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:s.doc);this.ownerDocumentBody=s.body(this.ownerDocument);o.add(this);this.buildRendering();var d;if(this.domNode){this._applyAttributes();var c=this.srcNodeRef;c&&c.parentNode&&this.domNode!==c&&(c.parentNode.replaceChild(this.domNode,c),d=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();d&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a=
this.constructor,b=a._setterAttrs;if(!b){var b=a._setterAttrs=[],d;for(d in this.attributeMap)b.push(d);var a=a.prototype,c;for(c in a)c in this.attributeMap||"_set"+c.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()})+"Attr"in a&&b.push(c)}var e={},f;for(f in this.params||{})e[f]=this[f];h.forEach(b,function(a){a in e||this[a]&&this.set(a,this[a])},this);for(f in e)this.set(f,e[f])},postMixInProperties:function(){},buildRendering:function(){if(!this.domNode)this.domNode=
this.srcNodeRef||this.ownerDocument.createElement("div");if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(h.map(a,function(a){return a+"Rtl"})));d.add(this.domNode,a)}},postCreate:function(){},startup:function(){if(!this._started)this._started=!0,h.forEach(this.getChildren(),function(a){if(!a._started&&!a._destroyed&&m.isFunction(a.startup))a.startup(),a._started=!0})},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},
destroy:function(a){function b(d){d.destroyRecursive?d.destroyRecursive(a):d.destroy&&d.destroy(a)}this._beingDestroyed=!0;this.uninitialize();h.forEach(this._connects,m.hitch(this,"disconnect"));h.forEach(this._supportingWidgets,b);this.domNode&&h.forEach(o.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);o.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?k.remove(this.domNode,
"widgetId"):b.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||b.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){h.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;m.isObject(a)?p.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(a,b,c){c=3<=arguments.length?c:this.attributeMap[a];
h.forEach(m.isArray(c)?c:[c],function(c){var e=this[c.node||c||"domNode"];switch(c.type||"attribute"){case "attribute":m.isFunction(b)&&(b=m.hitch(this,b));c=c.attribute?c.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;e.tagName?k.set(e,c,b):e.set(c,b);break;case "innerText":e.innerHTML="";e.appendChild(this.ownerDocument.createTextNode(b));break;case "innerHTML":e.innerHTML=b;break;case "class":d.replace(e,b,this[a])}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?
this[b.g]():this[a]},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var d=this[c.s];if(m.isFunction(d))var e=d.apply(this,Array.prototype.slice.call(arguments,1));else{var d=this.focusNode&&!m.isFunction(this.focusNode)?"focusNode":"domNode",f=this[d].tagName,j;if(!(j=u[f])){j=this[d];var l={},g;for(g in j)l[g.toLowerCase()]=!0;j=u[f]=l}g=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:c.l in j&&"function"!=typeof b||
/^aria-|^data-|^role$/.test(a)?d:null;null!=g&&this._attrToDom(a,b,g);this._set(a,b)}return e||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;this._created&&b!==c&&(this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+
a,{detail:{prevValue:c,newValue:b}}))},emit:function(a,b,c){b=b||{};if(void 0===b.bubbles)b.bubbles=!0;if(void 0===b.cancelable)b.cancelable=!0;if(!b.detail)b.detail={};b.detail.widget=this;var d,e=this["on"+a];e&&(d=e.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&n.emit(this.domNode,a.toLowerCase(),b);return d},on:function(a,b){var c=this._onMap(a);return c?g.after(this,c,b,!0):this.own(n(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){var c=b._onMap=
{},d;for(d in b.prototype)/^on/.test(d)&&(c[d.replace(/^on/,"").toLowerCase()]=d)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?o.findWidgets(this.containerNode):[]},getParent:function(){return o.getEnclosingWidget(this.domNode.parentNode)},connect:function(b,c,d){return this.own(a.connect(b,c,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(w.subscribe(a,
m.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:l.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=p.get(this.domNode,"display")},placeAt:function(a,c){var d=!a.tagName&&o.byId(a);d&&d.addChild&&(!c||"number"===typeof c)?d.addChild(this,c):(d=d?d.containerNode&&!/after|before|replace/.test(c||"")?d.containerNode:d.domNode:e.byId(a,this.ownerDocument),b.place(this.domNode,d,c),!this._started&&(this.getParent()||
{})._started&&this.startup());return this},getTextDir:function(a,b){return b},applyTextDir:function(){},defer:function(a,b){var c=setTimeout(m.hitch(this,function(){c=null;this._destroyed||m.hitch(this,a)()}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}})})},"dojo/Stateful":function(){define("dojo/Stateful",["./_base/declare","./_base/lang","./_base/array","dojo/when"],function(i,h,g,f){return i("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(a){var c=this._attrPairNames;
return c[a]?c[a]:c[a]={s:"_"+a+"Setter",g:"_"+a+"Getter"}},postscript:function(a){a&&this.set(a)},_get:function(a,c){return"function"===typeof this[c.g]?this[c.g]():this[a]},get:function(a){return this._get(a,this._getAttrNames(a))},set:function(a,c){if("object"===typeof a){for(var e in a)a.hasOwnProperty(e)&&"_watchCallbacks"!=e&&this.set(e,a[e]);return this}e=this._getAttrNames(a);var g=this._get(a,e);e=this[e.s];var d;"function"===typeof e?d=e.apply(this,Array.prototype.slice.call(arguments,1)):
this[a]=c;if(this._watchCallbacks){var b=this;f(d,function(){b._watchCallbacks(a,g,c)})}return this},_changeAttrValue:function(a,c){var e=this.get(a);this[a]=c;this._watchCallbacks&&this._watchCallbacks(a,e,c);return this},watch:function(a,c){var e=this._watchCallbacks;if(!e)var f=this,e=this._watchCallbacks=function(a,b,c,d){var g=function(d){if(d)for(var d=d.slice(),e=0,g=d.length;e<g;e++)d[e].call(f,a,b,c)};g(e["_"+a]);d||g(e["*"])};!c&&"function"===typeof a?(c=a,a="*"):a="_"+a;var d=e[a];"object"!==
typeof d&&(d=e[a]=[]);d.push(c);var b={};b.unwatch=b.remove=function(){var a=g.indexOf(d,c);-1<a&&d.splice(a,1)};return b}})})},"dijit/Destroyable":function(){define("dijit/Destroyable",["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(i,h,g){return g("dijit.Destroyable",null,{destroy:function(){this._destroyed=!0},own:function(){i.forEach(arguments,function(f){var a="destroyRecursive"in f?"destroyRecursive":"destroy"in f?"destroy":"remove",c=h.before(this,"destroy",function(c){f[a](c)});
h.after(f,a,function(){c.remove()},!0)},this);return arguments}})})},"dijit/registry":function(){define("dijit/registry",["dojo/_base/array","dojo/sniff","dojo/_base/unload","dojo/_base/window","./main"],function(i,h,g,f,a){var c={},e={},k={length:0,add:function(a){if(e[a.id])throw Error("Tried to register widget with id=="+a.id+" but that id is already registered");e[a.id]=a;this.length++},remove:function(a){e[a]&&(delete e[a],this.length--)},byId:function(a){return"string"==typeof a?e[a]:a},byNode:function(a){return e[a.getAttribute("widgetId")]},
toArray:function(){var a=[],b;for(b in e)a.push(e[b]);return a},getUniqueId:function(d){var b;do b=d+"_"+(d in c?++c[d]:c[d]=0);while(e[b]);return"dijit"==a._scopeName?b:a._scopeName+"_"+b},findWidgets:function(a,b){function c(a){for(a=a.firstChild;a;a=a.nextSibling)if(1==a.nodeType){var d=a.getAttribute("widgetId");d?(d=e[d])&&f.push(d):a!==b&&c(a)}}var f=[];c(a);return f},_destroyAll:function(){a._curFocus=null;a._prevFocus=null;a._activeStack=[];i.forEach(k.findWidgets(f.body()),function(a){a._destroyed||
(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var b=a.getAttribute&&a.getAttribute("widgetId");if(b)return e[b];a=a.parentNode}return null},_hash:e};return a.registry=k})},"dijit/main":function(){define("dijit/main",["dojo/_base/kernel"],function(i){return i.dijit})},"dojo/string":function(){define("dojo/string",["./_base/kernel","./_base/lang"],function(i,h){var g={};h.setObject("dojo.string",g);g.rep=function(f,a){if(0>=a||!f)return"";
for(var c=[];;){a&1&&c.push(f);if(!(a>>=1))break;f+=f}return c.join("")};g.pad=function(f,a,c,e){c||(c="0");f=""+f;a=g.rep(c,Math.ceil((a-f.length)/c.length));return e?f+a:a+f};g.substitute=function(f,a,c,e){e=e||i.global;c=c?h.hitch(e,c):function(a){return a};return f.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(f,d,b){f=h.getObject(d,!1,a);b&&(f=h.getObject(b,!1,e).call(e,f,d));return c(f,d).toString()})};g.trim=String.prototype.trim?h.trim:function(f){for(var f=f.replace(/^\s+/,""),
a=f.length-1;0<=a;a--)if(/\S/.test(f.charAt(a))){f=f.substring(0,a+1);break}return f};return g})},"dojo/cache":function(){define("dojo/cache",["./_base/kernel","./text"],function(i){return i.cache})},"dojo/text":function(){define("dojo/text",["./_base/kernel","require","./has","./_base/xhr"],function(i,h,g,f){var a;a=function(a,c,d){f("GET",{url:a,sync:!!c,load:d,headers:i.config.textPluginHeaders||{}})};var c={},e=function(a){if(a){var a=a.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,
""),c=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);c&&(a=c[1])}else a="";return a},k={},d={};i.cache=function(b,d,f){var g;"string"==typeof b?/\//.test(b)?(g=b,f=d):g=h.toUrl(b.replace(/\./g,"/")+(d?"/"+d:"")):(g=b+"",f=d);b=void 0!=f&&"string"!=typeof f?f.value:f;f=f&&f.sanitize;if("string"==typeof b)return c[g]=b,f?e(b):b;if(null===b)return delete c[g],null;g in c||a(g,!0,function(a){c[g]=a});return f?e(c[g]):c[g]};return{dynamic:!0,normalize:function(a,c){var d=a.split("!"),e=d[0];return(/^\./.test(e)?
c(e):e)+(d[1]?"!"+d[1]:"")},load:function(b,f,g){var b=b.split("!"),j=1<b.length,i=b[0],h=f.toUrl(b[0]),b="url:"+h,n=k,q=function(a){g(j?e(a):a)};i in c?n=c[i]:b in f.cache?n=f.cache[b]:h in c&&(n=c[h]);if(n===k)if(d[h])d[h].push(q);else{var r=d[h]=[q];a(h,!f.async,function(a){c[i]=c[h]=a;for(var b=0;b<r.length;)r[b++](a);delete d[h]})}else q(n)}}})}}});define("frontend/layer/widget-common",[],1);