//>>built
define("dojo-bootstrap/Tooltip","./Support,dojo/_base/declare,dojo/query,dojo/_base/lang,dojo/_base/window,dojo/on,dojo/mouse,dojo/dom-class,dojo/dom-attr,dojo/dom-style,dojo/dom-geometry,dojo/dom-construct,dojo/html,dojo/NodeList-dom,dojo/NodeList-manipulate,dojo/NodeList-traverse,dojo/domReady!".split(","),function(f,p,g,c,q,e,m,h,i,l,n,k){var o=p("Tooltip",null,{defaultOptions:{animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',
trigger:"hover",title:"",delay:0,html:!0},constructor:function(a,b){this.init("tooltip",a,b)},init:function(a,b,d){var j=this;this.domNode=b;this.type=a;this.options=this.getOptions(d);this.enabled=!0;if("click"===this.options.trigger)g(this.domNode).parents(".modal").on("hide",function(){j.hide(!1)}),this.eventActivate=this.options.selector?e(this.domNode,e.selector(this.options.selector,"click"),c.hitch(this,"toggle")):e(this.domNode,"click",c.hitch(this,"toggle"));else if("manual"!==this.options.trigger)a=
"hover"===this.options.trigger?m.enter:"focusin",b="hover"===this.options.trigger?m.leave:"focusout",this.options.selector&&(a=e.selector(this.options.selector,a),b=e.selector(this.options.selector,b)),this.eventActivate=e(this.domNode,a,c.hitch(this,"enter")),this.eventDeactivate=e(this.domNode,b,c.hitch(this,"leave"));this.options.selector?this._options=c.mixin({},c.mixin(c.clone(this.options),{trigger:"manual",selector:""})):this.fixTitle()},getOptions:function(a){a=c.mixin({},c.mixin(c.clone(this.defaultOptions),
c.mixin(a,f.getData(this.domNode))));if(a.delay&&"number"===typeof a.delay)a.delay={show:a.delay,hide:a.delay};return a},enter:function(a){var b=f.getData(a.target,this.type);b||(g(a.target)[this.type](this._options),b=f.getData(a.target,this.type));this.timeout&&clearTimeout(this.timeout);if(b){if(!b.options.delay||!b.options.delay.show)return b.show();b.hoverState="in";this.timeout=setTimeout(function(){"in"===b.hoverState&&b.show()},b.options.delay.show)}return this},leave:function(a){var b=f.getData(a.target,
this.type);b||(g(a.target)[this.type](this._options),b=f.getData(a.target,this.type));this.timeout&&clearTimeout(this.timeout);if(b){if(!b.options.delay||!b.options.delay.hide)return b.hide();b.hoverState="out";this.timeout=setTimeout(function(){"out"===b.hoverState&&b.hide()},b.options.delay.hide)}return this},show:function(){var a,b,d,j,c,f,e;if(this.hasContent()&&this.enabled){a=this.tip();this.setContent();this.options.animation&&"false"!==this.options.animation&&!1!==this.options.animation&&
h.add(a,"fade");f="function"===typeof this.options.placement?this.options.placement.call(this,a,this.domNode):this.options.placement;b=/in/.test(f);k.place(a,b?this.domNode:q.body(),"last");l.set(a,{top:0,left:0,display:"block"});d=this.getPosition(b);c=n.position(a);j=c.w;c=c.h;switch(b?f.split(" ")[1]:f){case "bottom":e={top:d.top+d.height+"px",left:d.left+d.width/2-j/2+"px"};break;case "top":e={top:d.top-c+"px",left:d.left+d.width/2-j/2+"px"};break;case "left":e={top:d.top+d.height/2-c/2+"px",
left:d.left-j+"px"};break;case "right":e={top:d.top+d.height/2-c/2+"px",left:d.left+d.width+"px"}}l.set(a,e);h.add(a,[f,"in"].join(" "))}},hide:function(a){function b(){var a=setTimeout(function(){d.hideEvent.remove()},500);d.hideEvent=e.once(c,f.trans.end,function(){clearTimeout(a);k.destroy(c);d.tipNode=null})}var d=this,a=a||!0,c=this.tip();h.remove(c,"in");f.trans&&h.contains(c,"fade")&&a?b():(k.destroy(c),d.tipNode=null);return this},setContent:function(){var a=this.tip(),b=this.getTitle();g(".tooltip-inner",
a)[this.options.html?"html":"text"](b);h.remove(a,"fade in top bottom left right")},hasContent:function(){return this.getTitle()},fixTitle:function(){if(i.get(this.domNode,"title")||"string"!==typeof i.get(this.domNode,"data-original-title"))i.set(this.domNode,"data-original-title",i.get(this.domNode,"title")||""),i.remove(this.domNode,"title")},getTitle:function(){return i.get(this.domNode,"data-original-title")||("function"===typeof this.options.title?this.options.title.call(this.domNode):this.options.title)},
getPosition:function(a){var b=n.position(this.domNode,!0);return c.mixin({},c.mixin(a?{top:0,left:0}:{top:b.y,left:b.x},{width:b.w,height:b.h}))},tip:function(){return this.tipNode=this.tipNode?this.tipNode:k.toDom(this.options.template)},validate:function(){if(!this.domNode.parentNode)l.set(this.domNode,"display","none"),this.options=this.domNode=null},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[h.contains(this.tip(),
"in")?"hide":"show"]()},destroy:function(){this.hide();this.eventActivate&&this.eventActivate.remove();this.eventDeactivate&&this.eventDeactivate.remove();f.removeData(this.domNode,"tooltip")}});c.extend(g.NodeList,{tooltip:function(a){var b=c.isObject(a)?a:{};return this.forEach(function(d){var e=f.getData(d,"tooltip");e||f.setData(d,"tooltip",e=new o(d,b));c.isString(a)&&e[a].call(e)})}});g("[data-toggle=tooltip]").tooltip();return o});