//>>built
require({cache:{"dojo-bootstrap/Affix":function(){define("dojo-bootstrap/Affix","./Support,dojo/_base/declare,dojo/query,dojo/_base/lang,dojo/_base/window,dojo/on,dojo/dom-class,dojo/dom-construct,dojo/dom-attr,dojo/dom-style,dojo/dom-geometry,dojo/NodeList-dom,dojo/NodeList-traverse,dojo/domReady!".split(","),function(g,j,i,f,e,a,b,d,c,w,y){var s=j([],{defaultOptions:{offset:0},constructor:function(d,c){this.options=f.mixin(f.clone(this.defaultOptions),c||{});this.domNode=d;a(e.global,"scroll",f.hitch(this,
"checkPosition"));this.checkPosition()},checkPosition:function(){if("none"!==w.get(this.domNode,"display")){var a=y.position(this.domNode,!1),d=e.doc.height,c=e.global.scrollY,b=this.options.offset,f;"object"!==typeof b?b=f=b:(f="function"===typeof b.top?b.top():b.top||0,b="function"===typeof b.bottom?b.bottom():b.bottom||0);d=null!==this.unpin&&c+this.unpin<=a.y?!1:null!==b&&a.y+a.h>=d-b?"bottom":null!==f&&c<=f?"top":!1;if(this.affixed!==d)this.affixed=d,this.unpin="bottom"===d?a.y-c:null,i(this.domNode).removeClass("affix affix-top affix-bottom").addClass("affix"+
(d?"-"+d:""))}}});f.extend(i.NodeList,{affix:function(a){var d=f.isObject(a)?a:{};return this.forEach(function(c){var b=g.getData(c,"affix");b||g.setData(c,"affix",b=new s(c,d));f.isString(a)&&b[a].call(b)})}});i("[data-spy=affix]").forEach(function(a){var d=g.getData(a);d.offset=d.offset||{};if(d["offset-bottom"])d.offset.bottom=d["offset-bottom"];if(d["offset-top"])d.offset.top=d["offset-top"];i(a).affix(d)});return s})},"dojo-bootstrap/Support":function(){define("dojo-bootstrap/Support","dojo/query,dojo/_base/lang,dojo/dom-attr,dojo/_base/array,dojo/_base/json,dojo/NodeList-data".split(","),
function(g,j,i,f,e){j.extend(g.NodeList,{show:function(){return this.forEach(function(a){a.style.display="block"})},hide:function(){return this.forEach(function(a){a.style.display="none"})}});var a=function(a){var c=g(a)[0];if(c){var e=this;f.forEach(c.attributes,function(c){0<=c.name.indexOf("data-")&&e.setData(a,c.name.substr(5),b(c.value))})}},b=function(a){return!a?void 0:0===a.indexOf("{")&&a.indexOf("}")===a.length-1?e.fromJson(a):0===a.indexOf("[")&&a.indexOf("]")===a.length-1?e.fromJson(a):
a};return{trans:function(){var a;a:{a=document.createElement("bootstrap");var c={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",transition:"transitionend"},b;for(b in c)if(void 0!==a.style[b]){a=c[b];break a}a=void 0}return a&&{end:a}}(),getData:function(d,c,e){c=c||void 0;e=e||void 0;if(void 0!==c&&j.isString(c)){var f=g(d).data(c);f&&void 0===f[0]&&(g(d)[0]&&(f=i.get(g(d)[0],"data-"+c)),void 0!==f&&(f=b(f)),void 0===f&&void 0!==e&&(f=this.setData(d,
c,e)));return j.isArray(f)&&0<f.length?f[0]:f}a.call(this,d);return g(d).data()[0]},setData:function(a,c,b){g(a).data(c,b);return b},removeData:function(a,c){return g(a).removeData(c)},toCamel:function(a){return a.replace(/(\-[a-z])/g,function(a){return a.toUpperCase().replace("-","")})},toDash:function(a){return a.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()})},toUnderscore:function(a){return a.replace(/([A-Z])/g,function(a){return"_"+a.toLowerCase()})}}})},"dojo/NodeList-data":function(){define("dojo/NodeList-data",
["./_base/kernel","./query","./_base/lang","./_base/array","./dom-attr"],function(g,j,i,f,e){var a=j.NodeList,b={},d=0,c=function(a){var c=e.get(a,"data-dojo-dataid");c||(c="pid"+d++,e.set(a,"data-dojo-dataid",c));return c},w=g._nodeData=function(a,d,e){var f=c(a),g;b[f]||(b[f]={});1==arguments.length&&(g=b[f]);"string"==typeof d?2<arguments.length?b[f][d]=e:g=b[f][d]:g=i.mixin(b[f],d);return g},y=g._removeNodeData=function(a,d){var e=c(a);b[e]&&(d?delete b[e][d]:delete b[e])};g._gcNodeData=function(){var a=
j("[data-dojo-dataid]").map(c),d;for(d in b)0>f.indexOf(a,d)&&delete b[d]};i.extend(a,{data:a._adaptWithCondition(w,function(a){return 0===a.length||1==a.length&&"string"==typeof a[0]}),removeData:a._adaptAsForEach(y)});return a})},"dojo/NodeList-traverse":function(){define("dojo/NodeList-traverse",["./query","./_base/lang","./_base/array"],function(g,j,i){var f=g.NodeList;j.extend(f,{_buildArrayFromCallback:function(e){for(var a=[],b=0;b<this.length;b++){var d=e.call(this[b],this[b],a);d&&(a=a.concat(d))}return a},
_getUniqueAsNodeList:function(e){for(var a=[],b=0,d;d=e[b];b++)1==d.nodeType&&-1==i.indexOf(a,d)&&a.push(d);return this._wrap(a,null,this._NodeListCtor)},_getUniqueNodeListWithParent:function(e,a){var b=this._getUniqueAsNodeList(e),b=a?g._filterResult(b,a):b;return b._stash(this)},_getRelatedUniqueNodes:function(e,a){return this._getUniqueNodeListWithParent(this._buildArrayFromCallback(a),e)},children:function(e){return this._getRelatedUniqueNodes(e,function(a){return j._toArray(a.childNodes)})},
closest:function(e,a){return this._getRelatedUniqueNodes(null,function(b){do if(g._filterResult([b],e,a).length)return b;while(b!=a&&(b=b.parentNode)&&1==b.nodeType);return null})},parent:function(e){return this._getRelatedUniqueNodes(e,function(a){return a.parentNode})},parents:function(e){return this._getRelatedUniqueNodes(e,function(a){for(var b=[];a.parentNode;)a=a.parentNode,b.push(a);return b})},siblings:function(e){return this._getRelatedUniqueNodes(e,function(a){for(var b=[],d=a.parentNode&&
a.parentNode.childNodes,c=0;c<d.length;c++)d[c]!=a&&b.push(d[c]);return b})},next:function(e){return this._getRelatedUniqueNodes(e,function(a){for(a=a.nextSibling;a&&1!=a.nodeType;)a=a.nextSibling;return a})},nextAll:function(e){return this._getRelatedUniqueNodes(e,function(a){for(var b=[];a=a.nextSibling;)1==a.nodeType&&b.push(a);return b})},prev:function(e){return this._getRelatedUniqueNodes(e,function(a){for(a=a.previousSibling;a&&1!=a.nodeType;)a=a.previousSibling;return a})},prevAll:function(e){return this._getRelatedUniqueNodes(e,
function(a){for(var b=[];a=a.previousSibling;)1==a.nodeType&&b.push(a);return b})},andSelf:function(){return this.concat(this._parent)},first:function(){return this._wrap(this[0]&&[this[0]]||[],this)},last:function(){return this._wrap(this.length?[this[this.length-1]]:[],this)},even:function(){return this.filter(function(e,a){return 0!=a%2})},odd:function(){return this.filter(function(e,a){return 0==a%2})}});return f})},"dijitive/ExpandingTextarea":function(){define("dijitive/ExpandingTextarea",["dojo/_base/declare",
"dojo/dom-attr","dijit/form/Textarea"],function(g,j,i){return g([i],{})})},"dijit/form/Textarea":function(){define("dijit/form/Textarea",["dojo/_base/declare","dojo/dom-style","./_ExpandingTextAreaMixin","./SimpleTextarea"],function(g,j,i,f){return g("dijit.form.Textarea",[f,i],{baseClass:"dijitTextBox dijitTextArea dijitExpandingTextArea",cols:"",buildRendering:function(){this.inherited(arguments);j.set(this.textbox,{overflowY:"hidden",overflowX:"auto",boxSizing:"border-box",MsBoxSizing:"border-box",
WebkitBoxSizing:"border-box",MozBoxSizing:"border-box"})}})})},"dijit/form/_ExpandingTextAreaMixin":function(){define("dijit/form/_ExpandingTextAreaMixin","dojo/_base/declare,dojo/dom-construct,dojo/has,dojo/_base/lang,dojo/on,dojo/_base/window,../Viewport".split(","),function(g,j,i,f,e,a,b){i.add("textarea-needs-help-shrinking",function(){var d=a.body(),c=j.create("textarea",{rows:"5",cols:"20",value:" ",style:{zoom:1,overflow:"hidden",visibility:"hidden",position:"absolute",border:"0px solid black",
padding:"0px"}},d,"last"),b=c.scrollHeight>=c.clientHeight;d.removeChild(c);return b});return g("dijit.form._ExpandingTextAreaMixin",null,{_setValueAttr:function(){this.inherited(arguments);this.resize()},postCreate:function(){this.inherited(arguments);var a=this.textbox;this.own(e(a,"scroll, focus",f.hitch(this,"_resizeLater")));a.style.overflowY="hidden";this._estimateHeight()},startup:function(){this.inherited(arguments);this.own(b.on("resize",f.hitch(this,"_resizeLater")));this._resizeLater()},
_onInput:function(a){this.inherited(arguments);this.resize()},_estimateHeight:function(){var a=this.textbox;a.style.height="auto";a.rows=(a.value.match(/\n/g)||[]).length+2},_resizeLater:function(){this.defer("resize")},resize:function(){function a(){var b=!1;if(""===c.value)c.value=" ",b=!0;var d=c.scrollHeight;if(b)c.value="";return d}var c=this.textbox;if("hidden"==c.style.overflowY)c.scrollTop=0;if(!this.busyResizing){this.busyResizing=!0;if(a()||c.offsetHeight){var b=c.style.height;if(!/px/.test(b))b=
a(),c.rows=1,c.style.height=b+"px";var b=Math.max(Math.max(c.offsetHeight,parseInt(b))-c.clientHeight,0)+a(),e=b+"px";if(e!=c.style.height)c.rows=1,c.style.height=e;if(i("textarea-needs-help-shrinking")){var f=a(),g=c.style.minHeight,j=4;c.style.minHeight=e;for(c.style.height="auto";0<b;){c.style.minHeight=Math.max(b-j,4)+"px";e=a();f-=e;b-=f;if(f<j)break;f=e;j<<=1}c.style.height=b+"px";c.style.minHeight=g}c.style.overflowY=a()>c.clientHeight?"auto":"hidden"}else this._estimateHeight();this.busyResizing=
!1}}})})},"dijit/Viewport":function(){define("dijit/Viewport","dojo/Evented,dojo/on,dojo/domReady,dojo/sniff,dojo/_base/window,dojo/window".split(","),function(g,j,i,f,e,a){var b=new g;i(function(){var d=a.getBox();b._rlh=j(e.global,"resize",function(){var c=a.getBox();d.h==c.h&&d.w==c.w||(d=c,b.emit("resize"))});if(8==f("ie")){var c=screen.deviceXDPI;setInterval(function(){if(screen.deviceXDPI!=c)c=screen.deviceXDPI,b.emit("resize")},500)}});return b})},"dojo/parser":function(){define("dojo/parser",
"require,./_base/kernel,./_base/lang,./_base/array,./_base/config,./_base/html,./_base/window,./_base/url,./_base/json,./aspect,./date/stamp,./Deferred,./has,./query,./on,./ready".split(","),function(g,j,i,f,e,a,b,d,c,w,y,s,C,F,G,H){function I(a){var c=a._nameCaseMap,b=a.prototype;if(!c||c._extendCnt<B){var c=a._nameCaseMap={},d;for(d in b)"_"!==d.charAt(0)&&(c[d.toLowerCase()]=d);c._extendCnt=B}return c}function D(a){var c=a.join();if(!x[c]){for(var d=[],b=0,e=a.length;b<e;b++){var f=a[b];d[d.length]=
x[f]=x[f]||i.getObject(f)||~f.indexOf("/")&&g(f)}a=d.shift();x[c]=d.length?a.createSubclass?a.createSubclass(d):a.extend.apply(a,d):a}return x[c]}var B=0;w.after(i,"extend",function(){B++},!0);var x={},E={_clearCache:function(){B++;x={}},_functionFromScript:function(a,c){var d="",b="",e=a.getAttribute(c+"args")||a.getAttribute("args"),g=a.getAttribute("with"),e=(e||"").split(/\s*,\s*/);g&&g.length&&f.forEach(g.split(/\s*,\s*/),function(a){d+="with("+a+"){";b+="}"});return new Function(e,d+a.innerHTML+
b)},instantiate:function(a,c,d){var c=c||{},d=d||{},b=(d.scope||j._scopeName)+"Type",e="data-"+(d.scope||j._scopeName)+"-",g=e+"type",i=e+"mixins",n=[];f.forEach(a,function(a){var d=b in c?c[b]:a.getAttribute(g)||a.getAttribute(b);if(d){var e=a.getAttribute(i),d=e?[d].concat(e.split(/\s*,\s*/)):[d];n.push({node:a,types:d})}});return this._instantiate(n,c,d)},_instantiate:function(a,d,c){a=f.map(a,function(a){var b=a.ctor||D(a.types);if(!b)throw Error("Unable to resolve constructor for: '"+a.types.join()+
"'");return this.construct(b,a.node,d,c,a.scripts,a.inherited)},this);!d._started&&!c.noStart&&f.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a},construct:function(a,b,e,g,z,r){var J;var s=a&&a.prototype,g=g||{},n={};g.defaults&&i.mixin(n,g.defaults);r&&i.mixin(n,r);var u;C("dom-attributes-explicit")?u=b.attributes:C("dom-attributes-specified-flag")?u=f.filter(b.attributes,function(a){return a.specified}):(r=(/^input$|^img$/i.test(b.nodeName)?b:b.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,
"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),u=f.map(r.split(/\s+/),function(a){var d=a.toLowerCase();return{name:a,value:"LI"==b.nodeName&&"value"==a||"enctype"==d?b.getAttribute(d):b.getAttributeNode(d).value}}));var k=g.scope||j._scopeName,r="data-"+k+"-",l={};"dojo"!==k&&(l[r+"props"]="data-dojo-props",l[r+"type"]="data-dojo-type",l[r+"mixins"]="data-dojo-mixins",l[k+"type"]="dojoType",l[r+"id"]="data-dojo-id");for(var k=0,h,t=[],v,o;h=u[k++];){var m=h.name,p=m.toLowerCase();h=
h.value;switch(l[p]||p){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":o=h;break;case "data-dojo-id":case "jsid":v=h;break;case "data-dojo-attach-point":case "dojoattachpoint":n.dojoAttachPoint=h;break;case "data-dojo-attach-event":case "dojoattachevent":n.dojoAttachEvent=h;break;case "class":n["class"]=b.className;break;case "style":n.style=b.style&&b.style.cssText;break;default:if(m in s||(m=I(a)[p]||m),m in s)switch(typeof s[m]){case "string":n[m]=h;
break;case "number":n[m]=h.length?Number(h):NaN;break;case "boolean":n[m]="false"!=h.toLowerCase();break;case "function":n[m]=""===h||-1!=h.search(/[^\w\.]+/i)?new Function(h):i.getObject(h,!1)||new Function(h);t.push(m);break;default:p=s[m],n[m]=p&&"length"in p?h?h.split(/\s*,\s*/):[]:p instanceof Date?""==h?new Date(""):"now"==h?new Date:y.fromISOString(h):p instanceof d?j.baseUrl+h:c.fromJson(h)}else n[m]=h}}for(k=0;k<t.length;k++)u=t[k].toLowerCase(),b.removeAttribute(u),b[u]=null;if(o)try{o=
c.fromJson.call(g.propsThis,"{"+o+"}"),i.mixin(n,o)}catch(A){throw Error(A.toString()+" in data-dojo-props='"+o+"'");}i.mixin(n,e);z||(z=a&&(a._noScript||s._noScript)?[]:F("> script[type^='dojo/']",b));e=[];g=[];o=[];t=[];if(z)for(k=0;k<z.length;k++){var q=z[k];b.removeChild(q);u=q.getAttribute(r+"event")||q.getAttribute("event");l=q.getAttribute(r+"prop");m=q.getAttribute(r+"method");p=q.getAttribute(r+"advice");h=q.getAttribute("type");q=this._functionFromScript(q,r);u?"dojo/connect"==h?e.push({method:u,
func:q}):"dojo/on"==h?t.push({event:u,func:q}):n[u]=q:"dojo/aspect"==h?e.push({method:m,advice:p,func:q}):"dojo/watch"==h?o.push({prop:l,func:q}):g.push(q)}J=(z=a.markupFactory||s.markupFactory)?z(n,b,a):new a(n,b),a=J;v&&i.setObject(v,a);for(k=0;k<e.length;k++)w[e[k].advice||"after"](a,e[k].method,i.hitch(a,e[k].func),!0);for(k=0;k<g.length;k++)g[k].call(a);for(k=0;k<o.length;k++)a.watch(o[k].prop,o[k].func);for(k=0;k<t.length;k++)G(a,t[k].event,t[k].func);return a},scan:function(a,b){function d(a){if(!a.inherited){a.inherited=
{};var b=a.node,c=d(a.parent),b={dir:b.getAttribute("dir")||c.dir,lang:b.getAttribute("lang")||c.lang,textDir:b.getAttribute(k)||c.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var c=[],e=[],i={},y=(b.scope||j._scopeName)+"Type",n="data-"+(b.scope||j._scopeName)+"-",w=n+"type",k=n+"textdir",n=n+"mixins",l=a.firstChild,h=b.inherited;if(!h){var t=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&t(a.parentNode,b)},h={dir:t(a,"dir"),lang:t(a,"lang"),textDir:t(a,
k)},v;for(v in h)h[v]||delete h[v]}for(var h={inherited:h},o,m;;)if(l)if(1!=l.nodeType)l=l.nextSibling;else if(o&&"script"==l.nodeName.toLowerCase())(p=l.getAttribute("type"))&&/^dojo\/\w/i.test(p)&&o.push(l),l=l.nextSibling;else if(m)l=l.nextSibling;else{var p=l.getAttribute(w)||l.getAttribute(y);v=l.firstChild;if(!p&&(!v||3==v.nodeType&&!v.nextSibling))l=l.nextSibling;else{m=null;if(p){var A=l.getAttribute(n);o=A?[p].concat(A.split(/\s*,\s*/)):[p];try{m=D(o)}catch(q){}m||f.forEach(o,function(a){~a.indexOf("/")&&
!i[a]&&(i[a]=!0,e[e.length]=a)});A=m&&!m.prototype._noScript?[]:null;h={types:o,ctor:m,parent:h,node:l,scripts:A};h.inherited=d(h);c.push(h)}else h={node:l,scripts:o,parent:h};l=v;o=A;m=m&&m.prototype.stopParser&&!b.template}}else{if(!h||!h.node)break;l=h.node.nextSibling;m=!1;h=h.parent;o=h.scripts}var x=new s;e.length?(C("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+e.join(", ")),g(e,function(){x.resolve(f.filter(c,function(a){if(!a.ctor)try{a.ctor=D(a.types)}catch(d){}for(var c=
a.parent;c&&!c.types;)c=c.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&!b.template);a.instantiate=!c||c.instantiate&&c.instantiateChildren;return a.instantiate}))})):x.resolve(c);return x.promise},_require:function(a){var a=c.fromJson("{"+a.innerHTML+"}"),b=[],d=[],e=new s,f;for(f in a)b.push(f),d.push(a[f]);g(d,function(){for(var a=0;a<b.length;a++)i.setObject(b[a],arguments[a]);e.resolve(arguments)});return e.promise},_scanAmd:function(a){var b=new s,c=b.promise;
b.resolve(!0);var d=this;F("script[type='dojo/require']",a).forEach(function(a){c=c.then(function(){return d._require(a)});a.parentNode.removeChild(a)});return c},parse:function(c,d){var e;!d&&c&&c.rootNode?(d=c,e=d.rootNode):c&&i.isObject(c)&&!("nodeType"in c)?d=c:e=c;e=e?a.byId(e):b.body();var d=d||{},f=d.template?{template:!0}:{},g=[],j=this,y=this._scanAmd(e,d).then(function(){return j.scan(e,d)}).then(function(a){return g=g.concat(j._instantiate(a,f,d))}).otherwise(function(a){console.error("dojo/parser::parse() error",
a);throw a;});i.mixin(g,y);return g}};j.parser=E;e.parseOnLoad&&H(100,E,"parse");return E})},"dojo/_base/url":function(){define("dojo/_base/url",["./kernel"],function(g){var j=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,i=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,f=function(){for(var e=arguments,a=[e[0]],b=1;b<e.length;b++)if(e[b]){var d=new f(e[b]+""),a=new f(a[0]+"");if(""==d.path&&!d.scheme&&!d.authority&&!d.query){if(null!=d.fragment)a.fragment=d.fragment;
d=a}else if(!d.scheme&&(d.scheme=a.scheme,!d.authority&&(d.authority=a.authority,"/"!=d.path.charAt(0)))){for(var a=(a.path.substring(0,a.path.lastIndexOf("/")+1)+d.path).split("/"),c=0;c<a.length;c++)"."==a[c]?c==a.length-1?a[c]="":(a.splice(c,1),c--):0<c&&!(1==c&&""==a[0])&&".."==a[c]&&".."!=a[c-1]&&(c==a.length-1?(a.splice(c,1),a[c-1]=""):(a.splice(c-1,2),c-=2));d.path=a.join("/")}a=[];d.scheme&&a.push(d.scheme,":");d.authority&&a.push("//",d.authority);a.push(d.path);d.query&&a.push("?",d.query);
d.fragment&&a.push("#",d.fragment)}this.uri=a.join("");e=this.uri.match(j);this.scheme=e[2]||(e[1]?"":null);this.authority=e[4]||(e[3]?"":null);this.path=e[5];this.query=e[7]||(e[6]?"":null);this.fragment=e[9]||(e[8]?"":null);if(null!=this.authority)e=this.authority.match(i),this.user=e[3]||null,this.password=e[4]||null,this.host=e[6]||e[7],this.port=e[9]||null};f.prototype.toString=function(){return this.uri};return g._Url=f})},"dojo/date/stamp":function(){define("dojo/date/stamp",["../_base/lang",
"../_base/array"],function(g,j){var i={};g.setObject("dojo.date.stamp",i);i.fromISOString=function(f,e){if(!i._isoRegExp)i._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var a=i._isoRegExp.exec(f),b=null;if(a){a.shift();a[1]&&a[1]--;a[6]&&(a[6]*=1E3);e&&(e=new Date(e),j.forEach(j.map("FullYear,Month,Date,Hours,Minutes,Seconds,Milliseconds".split(","),function(a){return e["get"+a]()}),function(b,c){a[c]=a[c]||b}));b=new Date(a[0]||
1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);100>a[0]&&b.setFullYear(a[0]||1970);var d=0,c=a[7]&&a[7].charAt(0);"Z"!=c&&(d=60*(a[8]||0)+(Number(a[9])||0),"-"!=c&&(d*=-1));c&&(d-=b.getTimezoneOffset());d&&b.setTime(b.getTime()+6E4*d)}return b};i.toISOString=function(f,e){var a=function(a){return 10>a?"0"+a:a},e=e||{},b=[],d=e.zulu?"getUTC":"get",c="";"time"!=e.selector&&(c=f[d+"FullYear"](),c=["0000".substr((c+"").length)+c,a(f[d+"Month"]()+1),a(f[d+"Date"]())].join("-"));b.push(c);if("date"!=
e.selector){c=[a(f[d+"Hours"]()),a(f[d+"Minutes"]()),a(f[d+"Seconds"]())].join(":");d=f[d+"Milliseconds"]();e.milliseconds&&(c+="."+(100>d?"0":"")+a(d));if(e.zulu)c+="Z";else if("time"!=e.selector)var d=f.getTimezoneOffset(),g=Math.abs(d),c=c+((0<d?"-":"+")+a(Math.floor(g/60))+":"+a(g%60));b.push(c)}return b.join("T")};return i})}}});
require("dojo-bootstrap/Affix,dijitive/Button,dijitive/Checkbox,dijitive/Radio,dijitive/Select,dijitive/Textarea,dijitive/ExpandingTextarea,dijitive/Textbox,dojo/query,dojo/parser,dojo/domReady!".split(","),function(g,j,i,f,e,a,b,d,c,w){w.parse();hljs.initHighlightingOnLoad();c(".bs-docs-sidenav").affix({offset:{top:function(){return 980>=document.width?245:195},bottom:270}});(new j({type:"submit","class":"btn btn-primary",label:'<i class="icon-music icon-white"></i> La La Laaaa',onClick:function(){console.info("Clicked");
return!1}},"button1")).startup();(new i({name:"menu",value:"clam chowder",checked:!0,onChange:function(){console.info("New value is: "+this.get("value"))}},"checkbox1")).startup();(new f({name:"size",value:"large",onChange:function(){console.info("New value is: "+this.get("value"))}},"radio1")).startup();(new f({name:"size",value:"small",checked:!0,onChange:function(){console.info("New value is: "+this.get("value"))}},"radio2")).startup();g=[{value:"",label:"Please select"},{value:"steak-and-lobster",
label:"Steak & Lobster"},{value:"clam-chowder",label:"Clam chowder"},{value:"pizza",label:"Pizza",disabled:!0},{value:"pasta",label:"Pasta"}];j=new e({name:"meal1",value:"pasta",options:g,required:!0,onChange:function(a){console.info("select.onChange(): "+a)}},"select1");j.watch("value",function(a,b,c){console.info('select.watch("value")',a,b,c)});j.watch("message",function(a,b,c){console[c?"error":"info"]('select.watch("message"):',c)});j.startup();e=new e({multiple:!0,name:"meal2",value:["steak-and-lobster",
"clam-chowder"],options:g,required:!0,onChange:function(a){console.info("select.onChange(): "+a)}},"select2");e.watch("value",function(a,b,c){console.info('select.watch("value")',a,b,c)});e.watch("message",function(a,b,c){console[c?"error":"info"]('select.watch("message"):',c)});e.startup();a=new a({name:"note",autocomplete:!1,uppercase:!0,trim:!0,onKeyPress:function(){console.info("Key pressed")}},"textarea1");a.startup();a.watch("value",function(a,c,b){console.info('New value is "'+b)});b=new b({name:"note",
autocomplete:!1,uppercase:!0,trim:!0,onKeyPress:function(){console.info("Key pressed")}},"expandingTextarea1");b.startup();b.watch("value",function(a,b,c){console.info('New value is "'+c)});d=new d({name:"title",placeHolder:"Your title",autocomplete:!1,uppercase:!0,trim:!0,onKeyPress:function(){console.info("Key pressed")}},"textbox1");d.startup();d.watch("value",function(a,c,b){console.info('New value is "'+b)})});